### ISSUE TITLE
Don't try to decode ip packets with offset eg. fragments

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#102]
_From [noro...@gmail.com](https://code.google.com/u/100262187313124309206/) on September 06, 2011 04:52:48_

What steps will reproduce the problem? 1. Dump fragmented udp traffic and it will some time decode the fragments with offset > 0 as UDP headers. What is the expected output? What do you see instead? Expected: Just IP pkt with data payload.
What we get: UDP headers when data is decodable. What version of the product are you using? On what operating system? SVN rev 82, Linux

**Attachment:** [dont-unpack-ip-fragments.patch](http://code.google.com/p/dpkt/issues/detail?id=75)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=75_

**Comment by sunhao2014** [comment]
Need `pcap` file to reproduce this problem.

**Comment by brifordwylie** [comment]
closing as not reproducible

**Comment by KnifeMaster007** [comment]
Here's example pcap file with fragmentation
[dump (1).zip](https://github.com/kbandla/dpkt/files/751309/dump.1.zip)

Steps to reproduce this problem:
`>>> from dpkt import pcap, ethernet`
`>>> cap = [ethernet.Ethernet(x[1]) for x in pcap.Reader(open('dump (1).pcap','rb'))]`
`>>> cap[0].data.offset`
`1480`
`>>> cap[0].data.mf`
`1`
`>>> type(cap[0].data.data)`
`<class 'dpkt.udp.UDP'>`

**Comment by KnifeMaster007** [comment]
Fixed in #329 pull request
