### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#103]
_From [johann....@gmail.com](https://code.google.com/u/118084747536112177642/) on September 25, 2011 11:02:57_

Attached is a patch for python3 support.
The patch is not pretty and not perfect, but it works for me.

Should work with versions 2.6-3.2, though i only tested it with python2.7 and python3.2. For versions < 2.6 there'd be a lot more work to do.

API break for py3k:
you have to use for example:
a = IP(b'asd')
b = bytes(a)
assert a == IP(b)

For py2 it should remain the same as before.

**Attachment:** [py3.patch](http://code.google.com/p/dpkt/issues/detail?id=76)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=76_

**Comment by kbandla** [comment]
_From [phihag.de@gmail.com](https://code.google.com/u/phihag.de@gmail.com/) on July 10, 2012 02:23:05_

Works fine here, but this patch requires six to be installed.

**Comment by kbandla** [comment]
_From [michael....@gmail.com](https://code.google.com/u/112876836618694680239/) on January 02, 2013 13:15:57_

Here is an additional patch for dpkt v1.7 enabling python3 support. This one is based on the johann's patch. There are no dependencies to be installed, six is no more needed for cdp. This would make dpkt the first python based packet-manipulation tool with python 3.x support! (eg scapy is still on v2.7)

**Attachment:** [dpkt_python_3.3.patch](http://code.google.com/p/dpkt/issues/detail?id=76#hc2)

**Comment by kbandla** [comment]
_From [XinmuOnT...@gmail.com](https://code.google.com/u/103330557569517964965/) on May 10, 2013 02:18:07_

I work on Windows 7 64bit and python 3.3 64bit, there are still some syntax errors after applying michael's patch, and I do some further patch stuff.
Because I'm really new for python and started with python 3.3 directly, maybe it goes wrong for some reason, becareful!!!
After all, I really hope this project to be ported to python 3 officially.

Sorry for my poor english.

**Attachment:** [mypy3.patch](http://code.google.com/p/dpkt/issues/detail?id=76#hc4)

**Comment by hgn** [comment]
Any intention to push python3 support now?

**Comment by jbremer** [comment]
I'm also interested in Python 3 support for `dpkt` for integration into another open source project, @cuckoosandbox.

**Comment by kbandla** [comment]
We have a few merge conflicts that need fixing, but we will make a release sometime this year.

**Comment by brifordwylie** [comment]
@jbremer the https://github.com/kbandla/dpkt/tree/migrate_py3 specifically.. :)

**Comment by brifordwylie** [comment]
Just a handy link for anyone working on this: http://python3porting.com/noconv.html

**Comment by jbremer** [comment]
Not saying I'll be doing much on this issue (unfortunately), but I did find @sunhao2014's porting notes interesting https://github.com/kbandla/dpkt/blob/migrate_py3/docs/Python3MigrationNotes.md - just in case I end up doing such work for @cuckoosandbox and related projects.. :-)
Anyway, hopefully somebody will step up :)

**Comment by kbandla** [comment]
@sunhao2014 did all the hard work. Our goal was to have native py3 support as far as possible (vs using 2to3). And, I have to say, he did a really good job. We will get to merging this with mainline this year. Many people have been asking for it.

**Comment by brifordwylie** [comment]
Closing this issue as the Python3 work has been completed
