### ISSUE TITLE
icmp6 type/code slip duplicate?

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#104]
_From [ruy.su...@gmail.com](https://code.google.com/u/102789873700722722337/) on September 27, 2011 10:32:33_

What steps will reproduce the problem? >>> print binascii.b2a_hex(buf)
002314008b3c000c29ea6fad86dd6000000000203afffe80000000000000020c29fffeea6fadfe80000000000000655dc7efb798391387000be800000000fe80000000000000655dc7efb79839130101000c29ea6fad
\>>> frame = dpkt.ethernet.Ethernet(buf)
\>>> print binascii.b2a_hex(str(frame))
002314008b3c000c29ea6fad86dd6000000000203afffe80000000000000020c29fffeea6fadfe80000000000000655dc7efb798391387000be887000be800000000fe80000000000000655dc7efb79839130101000c29ea6fad        

icmp6 type and code and the back 4bytes is duplicate unpacked. What is the expected output? What do you see instead? The above. What version of the product are you using? On what operating system? First line of icmp6.py
\# $Id: icmp6.py 23 2006-11-08 15:45:33Z dugsong $ Please provide any additional information below. ***** C:\DEV\PYTHON\ICMP6_ORIGINAL.PY
   71:          except (KeyError, dpkt.UnpackError):
   72:              self.data = buf
***** C:\DEV\PYTHON\ICMP6.PY
   71:          except (KeyError, dpkt.UnpackError):
   72:              pass
*****

Same icmp.py.
Maybe work.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=77_

**Comment by kbandla** [comment]
_From [ruy.su...@gmail.com](https://code.google.com/u/102789873700722722337/) on October 20, 2011 06:11:21_

It was the same problem as Issue 59 .
Sorry.

**Comment by sunhao2014** [comment]
Related to #86. I checked this issue. The problem still exists and could be reproduced by the following script.

``` python
from binascii import *
from dpkt import ethernet

buf = "\x00\x23\x14\x00\x8b\x3c\x00\x0c\x29\xea\x6f\xad\x86\xdd\x60\x00\x00\x00\x00\x20\x3a\xff\xfe\x80\x00\x00\x00\x00\x00\x00\x02\x0c\x29\xff\xfe\xea\x6f\xad\xfe\x80\x00\x00\x00\x00\x00\x00\x65\x5d\xc7\xef\xb7\x98\x39\x13\x87\x00\x0b\xe8\x00\x00\x00\x00\xfe\x80\x00\x00\x00\x00\x00\x00\x65\x5d\xc7\xef\xb7\x98\x39\x13\x01\x01\x00\x0c\x29\xea\x6f\xad"
print b2a_hex(buf)
frame = ethernet.Ethernet(buf)
print b2a_hex(str(frame))
```

The output is:

```
002314008b3c000c29ea6fad86dd6000000000203afffe80000000000000020c29fffeea6fadfe80000000000000655dc7efb798391387000be800000000fe80000000000000655dc7efb79839130101000c29ea6fad
002314008b3c000c29ea6fad86dd6000000000203afffe80000000000000020c29fffeea6fadfe80000000000000655dc7efb798391387000be887000be800000000fe80000000000000655dc7efb79839130101000c29ea6fad
```

I'm now trying on solving this issue...
