### ISSUE TITLE
Write timestamp arithmetic error

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#113]
_From [ruy.su...@gmail.com](https://code.google.com/u/102789873700722722337/) on March 13, 2012 11:18:36_

What steps will reproduce the problem? 1. In Writepkt, tv_usec contain arithmetic error.
   82:        tv_usec=int((float(ts) - int(ts)) * 1000000.0)
2. For example.
   \>>> ts = 123234345.667883
   \>>> int((float(ts) - int(ts)) * 1000000.0)
   667882
   ^^^^^^ will be 667883 ? What version of the product are you using? On what operating system? Python 2.7.2
dpkt-1.7 Please provide any additional information below. Only microsecond pcap.

diff -r a9f4cfba928f -r d599f177d81e dpkt/pcap.py
--- a/dpkt/pcap.py	Thu Jan 26 10:31:28 2012 +0900
+++ b/dpkt/pcap.py	Tue Mar 13 14:21:59 2012 +0900
@@ -79,7 +79,7 @@
         s = str(pkt)
         n = len(s)
         ph = PktHdr(tv_sec=int(ts),
-                    tv_usec=int((float(ts) - int(ts)) * 1000000.0),
+                    tv_usec=int(round((float(ts) - int(ts)),6) * 1000000.0),
                     caplen=n, len=n)
         self.__f.write(str(ph))
         self.__f.write(s)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=86_

**Comment by kbandla** [comment]
_From [ruy.su...@gmail.com](https://code.google.com/u/102789873700722722337/) on March 13, 2013 04:40:16_

No round(), will make correct...

ph = PktHdr(tv_sec=int(ts)&0xffffffff,
        tv_usec=int((ts * 1000000.0 - int(ts) * 1000000.0))&0xffffffff,
        caplen=n, len=origin_len)

**Comment by saylenty** [comment]
Maybe we should try using Decimal module here to solve this issue?

**Comment by sunhao2014** [comment]
I investigated this problem just now. @saylenty, I think using `Decimal` module is a good idea. Since the variable `ts` is of the type of `float`. Thus directly use `Decimal` won't work. Please see the following code.

``` python
>>> from decimal import *
>>> ts=123234345.667883
>>> int((Decimal(ts) - int(ts)) * Decimal('1000000.0'))
667882
```

Thus we need to explicitly set the precision as follows.

``` python
>>> getcontext().prec = 6
>>> int((Decimal(ts) - int(ts)) * Decimal('1000000.0'))
667883
```

In my opinion, using `round` directly would be a better choice. I've sent a PR on this issue.

**Comment by saylenty** [comment]
And why you decided that:
    ph = PktHdr(tv_sec=int(ts)&0xffffffff,
    tv_usec=int((ts * 1000000.0 - int(ts) * 1000000.0))&0xffffffff,
    caplen=n, len=origin_len)
doesn't clearer?

**Comment by sunhao2014** [comment]
I think using `round` makes the code more readable than the bit magic implementation. People may get confused if they see

``` python
tv_usec=int((ts * 1000000.0 - int(ts) * 1000000.0))&0xffffffff
```

without comments.

However using `round` can avoid this problem.

**Comment by saylenty** [comment]
I think you are right, however, the vast majority of individuals who looks source code is programmers and for them it wouldn't be a problem to understand what is going on here. Aditionally, bit operations are the fasterst ones.
One more thing, have a look at the my version:
    int(round (ts % 1 , 6) * 10 ** 6)
What are your views?

**Comment by sunhao2014** [comment]
Good idea. PR code updated.
