### ISSUE TITLE
vrrp.py has an initialization bug for the offset variable

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#114]
_From [timur.al...@gmail.com](https://code.google.com/u/117790548747779378711/) on March 18, 2012 23:45:23_

What steps will reproduce the problem? 1. Input packet:
p = '\x01\x00\x5e\x00\x00\x12\x00\x00\x5e\x00\x01\x36\x81\x00\x0a\x6c\x08\x00\x45\x00\x00\x1c\xff\xa2\x00\x00\xff\x70\x2a\x29\xfd\xf4\xe6\x9c\xd2\xda\xda\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

2. Parse with dpkt.ethernet.Ethernet(p)

3. There is a parsing error:
File "/usr/local/lib/python2.7/dist-packages/dpkt/vrrp.py", line 37, in unpack
    self.auth = self.data[off+4:]

The fix is to initialize off to 0 before the for loop. I attached the patch that fixes that. Anyone sees any problems with it?

**Attachment:** [vrrp.patch](http://code.google.com/p/dpkt/issues/detail?id=87)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=87_

**Comment by obormot** [comment]
the patch was already in, I've verified it by adding a unit test
