### ISSUE TITLE
'module' object has no attribute 'dport'

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#121]
_From [daw...@un0wn.org](https://code.google.com/u/105073676198660636692/) on September 02, 2012 22:47:34_

Hi,

According to the documentation, there should be an attribute called 'tcp.dport' in the tcp.py script. However when I try to call the object from the TCP class in tcp.py, I have an anttribute error as shown in the summary. I've already assigned eth.data to tcp, what seems to be the issue here?

My code: (I've tried)

dstport = dpkt.tcp.TCP.dport
dstport = dpkt.tcp.dport

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=95_

**Comment by kbandla** [comment]
_From [ali.huss...@ebryx.com](https://code.google.com/u/103555515379547882516/) on January 30, 2013 23:28:40_

I also got the same error while accessing dport

**Comment by kbandla** [comment]
_From [kyle.creyts@gmail.com](https://code.google.com/u/kyle.creyts@gmail.com/) on January 31, 2013 06:14:19_

will work much better when you actually use the right convention.

    for ts, buf in pcap:
        eth = dpkt.ethernet.Ethernet(buf)
        \#we only care about IP packets for now
        if eth.type != dpkt.ethernet.ETH_TYPE_IP:
            continue
        ip = eth.data
        \#example implements TCP data reading only
        if ip.p = 6:

            tcp = ip.data
            dstport=tcp.dport

**Comment by obormot** [comment]
not a bug, closing
