### ISSUE TITLE
dpkt.dpkt.UnpackError: invalid request: ''

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#122]
_From [daw...@un0wn.org](https://code.google.com/u/105073676198660636692/) on September 04, 2012 05:43:11_

What steps will reproduce the problem? 1. When I type in this line: http = dpkt.http.Request(tcp.data) What is the expected output? What do you see instead? I expect the script to run without any errors. What version of the product are you using? On what operating system? Python 2.7. The python script is meant to be cross-platform Please provide any additional information below. This is my code:

import dpkt, glob, pcap, socket, time

def delay():
    time.sleep(0.6) # delay execution of python script
    print "\n"

fileName = glob.glob("*.pcap") # finds all matching pathnames specified for .pcap files (hardcode for now)
print "Files present:",fileName
print ""

for files in fileName:
    f = open(files)
    print f
    delay()
    pcap = dpkt.pcap.Reader(f) #@UndefinedVariable
    pkt_counter = 0
    pkt_counter_relevant = 0
    pkt_counter_non_relevant = 0
    
    for ts, buf in pcap:
        pkt_counter += 1
        
        eth = dpkt.ethernet.Ethernet(buf)
    
        \# check if frame type is an IP packet
        if type(eth.data) == dpkt.ip.IP:
            
            if pkt_counter > 0:
                pkt_counter_relevant += 1
                last_time = ts
                ip = eth.data
                tcp = ip.data
                src = socket.inet_ntoa(ip.src)
                dst = socket.inet_ntoa(ip.dst)
                srcPort = tcp.sport
                dstPort = tcp.dport
                
                print "---------------"
                print "- Packet #&#37;d -" &#37; (pkt_counter) 
                print "---------------"
                print "Timestamp:",ts
                print "Bytes:",len(buf)
                print "Source IP/Port:",src,"/",srcPort
                print "Destination IP/Port:",dst,"/",dstPort
                
                \# check if it's a TCP/HTTP protocol
                if dstPort == 80:
                    delay()
                    print "Protocol: TCP/HTTP"
                    delay()
                    http = dpkt.http.Request(tcp.data)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=96_

**Comment by kbandla** [comment]
_From [daw...@un0wn.org](https://code.google.com/u/105073676198660636692/) on September 04, 2012 02:45:06_

Traceback (most recent call last):
    http = dpkt.http.Request(tcp.data) - my script
    self.unpack(args[0]) - dpkt http.py
    raise dpkt.UnpackError('invalid request: %r' % line) - dpkt http.py

**Comment by kbandla** [comment]
Need pcap to reproduce this issue.

**Comment by brifordwylie** [comment]
Closing as non-reproducible
