### ISSUE TITLE
dpkt.pcap support append mode.

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#130]
_From [ruy.su...@gmail.com](https://code.google.com/u/102789873700722722337/) on March 13, 2013 07:58:36_

dpkt.pcap.Writer always write libpcap Global-header when file opened.
Large pcap file parsing and created splitting output many files, will see "Too many open files".
Of course this is because I keep on opening the file...

Because I wanted to employ a dpkt.pcap.Writer to append packets to pcapfiles, will such a patch.

**Attachment:** [pcap.py.patch](http://code.google.com/p/dpkt/issues/detail?id=104)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=104_

**Comment by obormot** [comment]
What the patch author is suggesting is not the intended use of pcap.Writer. The class should be instantiated once, and then .writepkt() can be called multiple times to append packets to the file. As such, dpkt.pcap already supports append mode.

**Comment by ibeex** [comment]
What about writing to existing PCAP file, i think author used patch for that. How can you append to existing PCAP (one that was created with wireshark?)
