### ISSUE TITLE
STP Timers need to be shifted by 1 byte in stp.py

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#135]
_From [sm...@depht.com](https://code.google.com/u/114510700806104422691/) on June 04, 2013 10:40:11_

The following fields need to be right shifted by 8 bits in stp.py.
age, max_age, hello, fd

Both tcpdump and Wireshark displayed the correct values.  Whereas dpkt was wrong.

I tested this with the 802.1D Wireshark sample capture. http://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=stp.pcap I also attached a PVST+ capture I made where the same problem manifests.

Here is the diff.  There is probably a nicer way to handle this.  I just modeled this code on how I saw a similar situation handled in tcp.py.

17,20c17,20
\<         ('age', 'H', 0),
\<         ('max_age', 'H', 0),
\<         ('hello', 'H', 0),
\<         ('fd', 'H', 0)
\---
\>         ('age_x2', 'H', 0),
\>         ('max_age_x2', 'H', 0),
\>         ('hello_x2', 'H', 0),
\>         ('fd_x2', 'H', 0)
21a22,39
\> 
\>     def _get_age(self): return self.age_x2 >> 8
\>     def _set_age(self, age): self.age_x2 = age \<< 8
\>     age = property(_get_age, _set_age)
\> 
\>     def _get_max_age(self): return self.max_age_x2 >> 8
\>     def _set_max_age(self, max_age): self.max_age_x2 = max_age \<< 8
\>     max_age = property(_get_max_age, _set_max_age)
\> 
\>     def _get_hello(self): return self.hello_x2 >> 8
\>     def _set_hello(self, hello): self.hello_x2 = hello \<< 8
\>     hello = property(_get_hello, _set_hello)
\> 
\>     def _get_fd(self): return self.fd_x2 >> 8
\>     def _set_fd(self, fd): self.fd_x2 = fd \<< 8
\>     fd = property(_get_fd, _set_fd)
\> 
\>

**Attachment:** [dot1w.pcap](http://code.google.com/p/dpkt/issues/detail?id=109)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=109_

**Comment by brifordwylie** [comment]
Closed by PR #175
