### ISSUE TITLE
Unable to decode packets with both VLAN tag and MPLS label

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#140]
_From [marzetti...@gmail.com](https://code.google.com/u/110232804116673833794/) on October 01, 2013 03:37:05_

Even with last CVS dpkt is unable to decode packets that carry both VLAN tag and MPLS label.

I attached a "patch" to fix the issue.

**Attachment:** [ethernet.patch](http://code.google.com/p/dpkt/issues/detail?id=114)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=114_

**Comment by obormot** [comment]
cleanup.. this was addressed, closing
