### ISSUE TITLE
dpkt 1.8 does not build with python 2.4

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#142]
_From [ryandesi...@gmail.com](https://code.google.com/u/116893668111947003556/) on October 22, 2013 04:35:46_

What steps will reproduce the problem? 1. run "python2.4 setup.py build" What is the expected output? What do you see instead? Expected successful build but got:

Traceback (most recent call last):
  File "setup.py", line 4, in ?
    import dpkt
  File "/opt/local/var/macports/build/_Users_rschmidt_macports_dports_python_py-dpkt/py24-dpkt/work/dpkt-1.8/dpkt/__init__.py", line 62, in ?
    import ssl
  File "/opt/local/var/macports/build/_Users_rschmidt_macports_dports_python_py-dpkt/py24-dpkt/work/dpkt-1.8/dpkt/ssl.py", line 149
    padding = '\x00' if lenbytes == 3 else ''
                      ^
SyntaxError: invalid syntax What version of the product are you using? On what operating system? dpkt 1.8 on OS X 10.8.5 Please provide any additional information below. dpkt 1.7 built fine with Python 2.4 and the CHANGES file does not mention any change in requirements for version 1.8. So this is either a request to fix compatibility with python 2.4 or document that python 2.5 is now required.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=116_

**Comment by kbandla** [comment]
_From [kbandla@in2void.com](https://code.google.com/u/kbandla@in2void.com/) on December 29, 2014 12:45:07_

This was introduced in ssl.py (in r83 , older was r46 ). This is PEP 308 style code and now requires python2.5 or later to work. 
I propose we fix this to make it work with python2.4

**Status:** Accepted  
**Owner:** kbandla@in2void.com

**Comment by Saylenty** [comment]
@kbandla I'm wondering if this issue is actual?

**Comment by kbandla** [comment]
hah yes, this is actual. The code in question is:
```
    padding = '\x00' if lenbytes == 3 else ''
```
This is [PEP 308](https://www.python.org/dev/peps/pep-0308/) style, which is unsupported in python2.4

**Comment by Saylenty** [comment]
@kbandla Yes, I see that ternary operator (conditional expression) was added there. Ok, How about rewriting this without this operator using "old school" if else?
By the way, are there people that still use python 2.4? I think, if a project (which is uses python 2.4) is alive, developers have to modify it occasionally, because everything is changing very fast :)

**Comment by kbandla** [comment]
That is True. However, sometimes its hard to radically change deployed production code. 
I was planning to just rewrite this using simple if-else. 
Were this a situation where it was getting difficult to support python2.4, we would have dropped support for it and moved on to pyhton2.5 as the minimum requirement. Also, a lot of this will actually change when we get closer to python3 compatibility.

**Comment by brifordwylie** [comment]
So I understand the desire to support long running production use cases where the installation may have an 'ancient' python. As we go down the Python 3 road we will most likely have to face some hard realities. Even in the immediate term, TravisCI only goes back to 2.6 (so we can't even include 2.4 and 2.5 in our CI process).

**Comment by kbandla** [comment]
Totally agreed. I did not want to confirm this right away, but python 2.4 support will go away. Infact, we might end up supporting 2.7 and later. Lets see how this goes :)

**Comment by kbandla** [comment]
We are only going to support python 2.6 and later for dpkt 2.0
