### ISSUE TITLE
Landscape Error Cleanup

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#15]
https://landscape.io/github/kbandla/dpkt/29/messages/error

Someone just needs to go through these and figure out what's going on, if real error fix, if not real error put in a comment why it's fine.

**Comment by kbandla** [comment]
This is not a real error. The property in question is populated at runtime by the base packet class based on the value of __hdr__.

**Comment by brifordwylie** [comment]
Ah okay, so if all 11 errors are 'mis-marked' than I'll just close this issue.

**Comment by kbandla** [comment]
Yes, all those 11 are non-errors. We can go ahead and close this issue. 

We could 'fix' these [errors](https://github.com/kbandla/dpkt/blob/master/dpkt/icmp.py#L116-L117) by doing something like this:
```
if not hasattr(self, 'sum'):
    self.sum = dpkt.in_cksum(dpkt.Packet.__str__(self))
```
However, `hasattr` (and `getatrr`) internally use `try/except`. So its faster to use 'try/except' instead. But again, all this just to make the linter happy. This is a non-issue at runtime..

**Comment by brifordwylie** [comment]
Closing Issue
