### ISSUE TITLE
ip total length header field not stored correctly

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#156]
_From [stepan.k...@gmail.com](https://code.google.com/u/104710015789030975810/) on August 28, 2014 10:55:16_

What steps will reproduce the problem? >>> from dpkt.ip import IP
\>>> ip = IP(src='\x01\x02\x03\x04', dst='\x05\x06\x07\x08', p=1)
\>>> len(ip)
20
\>>> ip.opts='foo'
\>>> len(ip)
23
\>>> ip2=IP(str(ip))
\>>> len(ip2)
20

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=130_

**Comment by sunhao2014** [comment]
I investigated this issue just now. The problem can be reproduced by the code provided by Stepan. The key point is, when we create IP object by
``` python
ip = IP(src='\x01\x02\x03\x04', dst='\x05\x06\x07\x08', p=1)
```
The `IHL` and `Total Length` field of IP header have been set.
However, when we update the `Options` field by 
``` python
ip.opts='foo'
```
The two fields related to length haven't been updated. 

Thus my question is should we allow the user to update the `opts` and `data` fields after the IP object initialization? If so, we could provide a setter to those fields, by using the setter, we can both update the field together with the header parts related to length.

**Comment by kbandla** [comment]
Yes, updating the the ihl and len would be ideal. setter/getter approach should do it.

**Comment by sunhao2014** [comment]
Sure. I'll send a PR for this later this day.

**Comment by sunhao2014** [comment]
@kbandla, I checked some of the existing codes, and found when the user update the `opts` and `data` fields of `IP` object, they'll first update the data, then following a statement which updates the length fields of the head. For instance, in `test_ip()` function of `IP` module, there are the following snippets.
``` python
    s = 'E\x00\x00"\x00\x00\x00\x00@\x11r\xc0\x01\x02\x03\x04\x01\x02\x03\x04\x00o\x00\xde\x00\x0e\xbf5foobar'
    ip = IP(id=0, src='\x01\x02\x03\x04', dst='\x01\x02\x03\x04', p=17)
    u = udp.UDP(sport=111, dport=222)
    u.data = 'foobar'
    u.ulen += len(u.data)
    ip.data = u
    ip.len += len(u)
    assert (str(ip) == s)
```
Please notice when the user updates the `data` field, he'll manually update the `len` field.

At first, I plan to add some setters with `@property` decreator, however this implementation would affect the existing client code. I think this is an issue need to be discussed.

One alternative solution is add some setters explicitly, which look like `set_opts_with_len()`, to update the `opts` field and `len` field simultaneously.  Or do you have any good ideas for this problem?

**Comment by obormot** [comment]
@sunhao2014 I think a simple solution is:
```python
    def __str__(self):
+       self.len = self.__len__()
        if self.sum == 0:
            ...
```
Note that this breaks ```test_opt()``` test, and for a reason: the test is not correct. You can see the length field in the string is ```\x50```, while ```len(s) == 60```. Seems like whoever added this test has chopped off the TCP layer, and forgot to correct the length and the checksum. So this test will need to be fixed/replaced as well.

**Comment by kbandla** [comment]
Looks like the test failed. See https://travis-ci.org/kbandla/dpkt/jobs/71003850

**Comment by sunhao2014** [comment]
Already fixed. Closing.
