### ISSUE TITLE
Patch for /trunk/dpkt/pcap.py

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#157]
_From [leuzzsor...@gmail.com](https://code.google.com/u/103165636888744089243/) on September 01, 2014 18:36:43_

Make possible to read from STDIN

**Attachment:** [pcap.py.patch](http://code.google.com/p/dpkt/issues/detail?id=131)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=131_

**Comment by obormot** [comment]
dup of #129
