### ISSUE TITLE
multiple IPv6 extension headers of the same type aren't handled 

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#159]
_From [nux...@gmail.com](https://code.google.com/u/106810974862880856166/) on September 12, 2014 12:41:21_

dpkt stores ipv6 extension headers in a way that only allows it to store one extension header of each type.

While most of the headers may only appear once, the destination options header is allowed to appear twice and dpkt will only keep the 2nd copy when parsing a packet. In general it would be nice if invalid packets containing multiple instances of any of the options was parsed too.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=133_

**Comment by obormot** [comment]
fixed by merging #412
