### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#16]
Lets get permission from Jeff Silverman to use http://www.commercialventvac.com/dpkt.html as a starting point to fill in some real documentation on https://dpkt.readthedocs.org. Issue #7 also has a bullet  for documentation but given the importance wanted to call this out separately.

**Comment by Saylenty** [comment]
@brifordwylie , do you think that Doxygen (or tools the like) would give worse doc than Jeff Silverman has?

**Comment by brifordwylie** [comment]
Alexander,

That's a fair point... the documentation that Jeff has is admittedly super
rough and in the end we may not end up using much of it. Most likely we'll
just use Sphinx with autosummary for generating the API scaffolding..
http://sphinx-doc.org/ext/autosummary.html

**Comment by Saylenty** [comment]
@brifordwylie, Good choise! However, I could recomend Dexy (http://www.dexy.it/) which is used by Buildbot. What are your views?

**Comment by brifordwylie** [comment]
@Saylenty looks interesting (I might use it on another project)... might be a bit too bleeding edge for this project. I've basically already setup the scaffolding for sphinx/readthedocs, that's a fairly well known and adopted path, so we'll probably go with that for now.

**Comment by brifordwylie** [comment]
closed with PR #18
