### ISSUE TITLE
Check if a given dpkt-layer is part of the packet

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#165]
_From [anders.a...@gmail.com](https://code.google.com/u/117205048115784099846/) on April 20, 2015 02:58:52_

Is there a standard method for searching the data-portion of a packet for a given layer?

I have started to build a decoder for EtherNet/IP. When I sniff packets I usually need to filter for a given layer (ex. ForwardOpen etc). I did not find a method for this so I created the following two methods in dpkt.Packet:

dpkt.Packet.HasLayer( LayerClass )
dpkt.Packet.GetLayer( LayerClass )

They are basically recursive methods that check the Type of the data attribute of the packet.

The first one return True/False if the layer is located somewhere in the current packet, and the second of course return the layer in question (The first on actually run the second). 

I'm running Python 2.7.5 on windows 7 and 1.8 of dpkt.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=139_

**Comment by obormot** [comment]
I think these would look better as ```__contains__``` and ```__getitem__``` magic methods. E.g.
```python
pkt = Ethernet(buf)
if UDP in pkt:
    udp = pkt[UDP]
```
