### ISSUE TITLE
Google Code closing

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#166]
_From [he...@nerv.fi](https://code.google.com/u/114775857449284690653/) on May 30, 2015 05:13:57_

Google Code service is closing. Do you have plans to move this project to GitHub or similar hosting service?

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=140_

**Comment by kbandla** [comment]
_From [kbandla@in2void.com](https://code.google.com/u/kbandla@in2void.com/) on June 03, 2015 18:11:39_

Current project development is ongoing here: https://github.com/kbandla/dpkt

**Comment by brifordwylie** [comment]
So someone needs to do the 'URL Redirection' part of migration (https://code.google.com/p/support-tools/wiki/MigratingToGitHub#URL_Redirection). @kbandla can you do this or does @dugsong need to do it?

**Comment by kbandla** [comment]
Done.
