### ISSUE TITLE
make pcap.Reader compatible with StringIO

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#168]
Currently pcap.Reader expects a file object. 

It would be nice if it also accepts either a 
* file object
* a StringIO object 
* pcap bytes a string

**Comment by obormot** [comment]
Let's make sure to keep it running in streaming fashion (as a generator). One of the main advantages of dpkt over scapy in pcap processing is that it doesn't load the whole file in memory and therefore is suitable to process very large files.

Additionally we should make both Reader and Writer understand pcap-ng format. I have some code that does this, will create a separate issue unless it exists already.

**Comment by kbandla** [comment]
+1 reg generator @obormot. pcap-ng support would be nice! Lets track that as another issue. 
Also, just noticed that this issue (StringIO) is a dup of #143.

**Comment by obormot** [comment]
@kbandla Ok, I've created #169 for pcap-ng.
