### ISSUE TITLE
Support pcap-ng file format

### ISSUE THREAD

**Issue by obormot** [kbandla/dpkt#169]
pcap.Reader and pcap.Writer should be compatible with pcap-ng.

**Comment by brifordwylie** [comment]
Big +1 on this, @obormot I'll volunteer to work on this if you can organize it. I just don't want to go off in the wrong direction. In a vacuum I'd probably start by poking around on https://github.com/rshk/python-pcapng.

**Comment by obormot** [comment]
@brifordwylie looks like the project you've referenced can read but can not write pcap-ng files. I have my own code that does both. Let me look into it and come up with a proposal.

**Comment by songlinjian** [comment]
this issue resolved or not? I have a problem using dkpt parsing pcap-ng file and pcap file with raw ip encap.

**Comment by obormot** [comment]
@songlinjian pcapng is work in progress
