### ISSUE TITLE
New PyPI Release

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#173]
It's been a while we should push a 1.8.7 pypi release. @kbandla lets sync up when a good time for this is.. perhaps we'll wait until a few more items get complete and then push.

**Comment by kbandla** [comment]
Sure. I was going to create some milestones, so that its easy for us to cut a release.

**Comment by pstoll** [comment]
@kbandla - The version on PyPy seems like it is from quite a while ago. I need some newer changes (pcapng and also removing the seek call out of pcap.Reader.__iter__ to handle truly streaming files). 
Anything I can do to help move this along?

**Comment by brifordwylie** [comment]
@kbandla I went ahead and pushed a new release (1.8.7) so Pypi is updated and we should merge this in when you get a chance to look at it https://github.com/kbandla/dpkt/pull/257

**Comment by pstoll** [comment]
much appreciated.

**Comment by kbandla** [comment]
Thanks @brifordwylie !
