### ISSUE TITLE
Kanban Board for dpkt

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#174]
@kbandla There are two popular options huboard.com and waffle.io, I've used waffle on another project https://waffle.io/supercowpowers/workbench and it worked great, I don't have any experience with huboard but assume that it's also good. Ask around if we don't get any additional data points I'll probably go with waffle.

**Comment by brifordwylie** [comment]
Okay, so I popped this up https://waffle.io/kbandla/dpkt

**Comment by kbandla** [comment]
Nice! I just had a look at huboard, but i think waffle looks better
