### ISSUE TITLE
Refactor Readme

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#176]
The current readme.md and readme.rst is because PyPI will not render the markdown correctly. I want to refactor both of these files so they are very short and just point people to the official documentation.

**Comment by kbandla** [comment]
Ah sure. I didnt know that. I will fix it and make it a mininal rst document

**Comment by kbandla** [comment]
Fixed in 93133efa7a438d3b34ac627327f140356c7408f5
