### ISSUE TITLE
Fix Coveralls

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#178]
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

**Comment by kbandla** [comment]
just revoked and re-init coveralls' token

**Comment by brifordwylie** [comment]
Yeah, no sure what's going on.. but when I go here.
https://coveralls.io/builds/2820878/source?filename=dpkt%2Faim.py

It says this at the bottom:
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

**Comment by kbandla** [comment]
Just checked and the oauth is gone again. I will investigate and fix this later today.

**Comment by kbandla** [comment]
I have checked everything again and also revoked+init'd new OAuth token. Nothing worked. I am now going to delete the repo on coveralls.io and set it up again.

**Comment by brifordwylie** [comment]
Fixed
