### ISSUE TITLE
Detect application layer protocol from a cap file

### ISSUE THREAD

**Issue by kaatish** [kbandla/dpkt#179]
Hi,
Is it possible to extract an application layer protocol from a pcap file using dpkt? If so, how do I go about it. Currently, I can extract the transport protocol using the pcap and ethernet modules but I am interested in more than that.

**Comment by kbandla** [comment]
dpkt surely can. See the examples in the readme and the documentation. Is there something very specific you are looking for?

**Comment by kaatish** [comment]
Thanks for your response! Yes, I have been going through the documentation. Right now, I am reading the pcap files in somewhat similar fashion to one of the examples on the documentation page:

```
def ip_to_str(address):
    return socket.inet_ntop(socket.AF_INET, address)

def parsePCAP(fileName):
    with open(fileName) as f:
        pcap = dpkt.pcap.Reader(f)
        for ts, buf in pcap:
            eth = dpkt.ethernet.Ethernet(buf)
            if eth.type != dpkt.ethernet.ETH_TYPE_IP:
               continue
            ip = eth.data
            tcp = ip.data
            dts = datetime.datetime.fromtimestamp(ts)
            timestampprint = str(dts.hour)+':'+str(dts.minute)+':'+str(dts.second)
            recordinfo = ip_to_str(ip.src)+' '+ip_to_str(ip.dst)
            ethtype = str(tcp.sport)+' '+str(tcp.dport)+' '+str(ip.p)
            print(timestampprint+' '+recordinfo+' '+ethtype)
```
The value `ip.p` shows me the transport layer protocol (in my case 6 for TCP and 17 for UDP), which I am not really interested in right now. I would like to print a string for any application layer protocol in the packet (eg. HTTP, FTP, SSH, etc.).

**Comment by kbandla** [comment]
understood. If what you are looking for is just plain payload for each http packet, then you can do this by simply extending the above code:

```
...
dts = datetime.datetime.fromtimestamp(ts)
timestampprint = str(dts.hour)+':'+str(dts.minute)+':'+str(dts.second)
recordinfo = ip_to_str(ip.src)+' '+ip_to_str(ip.dst)
ethtype = str(tcp.sport)+' '+str(tcp.dport)+' '+str(ip.p)
print(timestampprint+' '+recordinfo+' '+ethtype)
if tcp.dport == 80:
    # This is http, parse the tcp payload as such
    http = dpkt.http.Request(tcp.data)
...
```
You can follow the rest [here](https://jon.oberheide.org/blog/2008/10/15/dpkt-tutorial-2-parsing-a-pcap-file/). 
But if you are looking for the complete tcp stream, you will need to first collect all the packets in the tcp stream, and reassemble them. Only then you can see the whole payload.

**Comment by kaatish** [comment]
Thanks! That solved it.
