### ISSUE TITLE
Python 3 compatibility / old patches

### ISSUE THREAD

**Issue by riklaunim** [kbandla/dpkt#189]
I've published old 1.7 dpkt package that I used in one project. It's Python3 compatible based on patches from Google Code etc., but compared to current master there is a lot of changes, so the diff is very big and quite hard to split https://github.com/riklaunim/dpkt/commit/0b74ba595f1cea42496e9ec14595c7c62b08ae61

**Comment by kbandla** [comment]
thats true @riklaunim. We were planning on add in py3 support this summer. @sunhao2014 was going to start work on it. Thanks for sharing that commit; we will surely use it.

**Comment by sunhao2014** [comment]
Yeah, I'll focus on this issue later this summer.

**Comment by brifordwylie** [comment]
Closing this issue as the Python3 work has been completed
