### ISSUE TITLE
dpkt.stun ignores padding

### ISSUE THREAD

**Issue by birnbap** [kbandla/dpkt#202]
in tlv padding is ignored
currently : 

 buf = buf[n + l:]

should be 
    padding = (4- l%4 )%4
    buf = buf[n+l+ padding:]

**Comment by obormot** [comment]
@birnbap example?

**Comment by kbandla** [comment]
This looks like a valid issue:
```
   The value in the length field MUST contain the length of the Value
   part of the attribute, prior to padding, measured in bytes.  Since
   STUN aligns attributes on 32-bit boundaries, attributes whose content
   is not a multiple of 4 bytes are padded with 1, 2, or 3 bytes of
   padding so that its value contains a multiple of 4 bytes.  The
   padding bits are ignored, and may be any value.
```
But yes, an example pcap would be nice. We need a pcap corpus..

**Comment by birnbap** [comment]
There is an example in cloudshark 
https://www.cloudshark.org/captures/4686b8430477

In the 7th frame - the first attribute (USER NAME) has padding
