### ISSUE TITLE
Provide both Python 2 and 3 support for metaclass.

### ISSUE THREAD

**Issue by sunhao2014** [kbandla/dpkt#205]
This is a problem I met when migrating the `dpkt` to Python 3.

We use metaclass in `dpkt.py` module. Unfortunately the syntax of metaclass in Python 2 and 3 are not the same. 

_Python 2_
``` python
class Packet(object):
    __metaclass__ = _MetaPacket
```

_Python 3_
``` python
class Packet(object, metaclass=_MetaPacket):
```

Using `six`, we can provide compatibility to both Python 2 and 3.
_Python 2 & 3_
``` python
with_metaclass(_MetaPacket, object)
```

However the problem is we introduce additional dependency to our project. According to Kiran's suggestion, we can avoid using `six` by adding two files named `dpkt2.py` and `dpkt3.py`, respectively providing support for Python 2 and 3.

Therefore we have two choices, selecting the related version during setup time or importing the related version at running time.

If we select the related version during setup time, we'll install the correct version of `dpkt` module when the user install the library. For instance, if the user run `python3 setup.py`, then we'll load `dpkt3.py`.

If we import the related version at running time, for instance, we'll import `dpkt3.py` if the `sys.version_info` is greater or equal to 3.

Thus which one do you think is better to provide both Python 2 and 3 support for metaclass?

**Comment by kbandla** [comment]
The idea is to have `dpkt2.py` and `dpkt3.py`, which have the metaclass code for Pyhton2 and 3 respectively. The `dpkt.py` module would simply load the appropriate module based on the python version. We can do this at runtime, or at setup-time. 
If we do this at setup, `setup.py` will pick the appropriate dpkt module and install it as `dpkt.py`.

**Comment by sunhao2014** [comment]
Issue already solved. Closing.
