### ISSUE TITLE
Should we drop Python 2.5 and older Python support in dpkt 2.0?

### ISSUE THREAD

**Issue by sunhao2014** [kbandla/dpkt#209]
Hi there,

Recently I was working on migrating `dpkt` to Python 3, which is an important feature of dpkt 2.0. I discussed with @kbandla early today about dropping the support for Python 2.5 and older versions in our new release. Because we suppose there are not so many users still run our packet on those old Python machines, also it will make it easier for our migration job. For instance, in Python 2 iterators have a `.next()` method we use to get the next value from the iterator. For example,

``` python
>>> i = iter(range(5))
>>> i.next()
0
>>> i.next()
1
```

This special method has in Python 3 been renamed to `.__next__()` to be consistent with the naming of special attributes elswhere in Python. However, we should generally not call it directly, but instead use the builtin is `next()` function. _However, this function is only available from Python 2.6._

There are also some similar issues for the migration to Python 3. Thus what's your opinion? Should we just drop the support for old Python versions (<= 2.5)?

Thanks,
Hao

**Comment by obormot** [comment]
2.5 is almost 9 years old at this point. Agree on dropping support for it.

**Comment by kbandla** [comment]
I think its in the best interest of the project to drop support for python 2.5 and older. dpkt should support python 2.6 and later.

**Comment by sunhao2014** [comment]
Okay, I think we can apply this Python version support change in `dpkt 2.0`.
