### ISSUE TITLE
IP.len not equal to IP.__len__()

### ISSUE THREAD

**Issue by yangbh** [kbandla/dpkt#218]
my env: mac os 10.10.5, python2.7, dpkt 1.8.6.2
$ pip list |grep dpkt
dpkt (1.8.6.2)

![dpkt](https://cloud.githubusercontent.com/assets/7778764/9866745/e43c183c-5b98-11e5-8fd3-c33be6ff4a4a.jpg)

actually, i.len is 40, not 20

i notice the code of ip.py, it seems self.len = self.**len**() doesn't execute, i don't know why
    def **str**(self):
        self.len = self.**len**()
        if self.sum == 0:

3qu guys

**Comment by dufferzafar** [comment]
I am unable to reproduce this. And there doesn't seem anything wrong with the dpkt's codebase either. If you could maybe reproduce this again, and provide us with the exact code (not a screenshot please) then that would be great. :)

**Comment by obormot** [comment]
cleaning up old issues.
can't reproduce on current master, `ip.len == ip.__len__() == 40`. closing
