### ISSUE TITLE
Python 2.6.6 import dpkt error

### ISSUE THREAD

**Issue by kasonbin** [kbandla/dpkt#223]
Python 2.6.6
pip install dpkt is ok!
but,test dpkt error:
>>> from dpkt.ip import IP 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ip
>>> from dpkt.icmp import ICMP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named icmp
>>> import sys
>>> print sys.path
['', '/usr/lib/python2.6/site-packages/setuptools-18.3.2-py2.6.egg', '/usr/lib/python2.6/site-packages/pip-7.1.2-py2.6.egg', '/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg', '/usr/lib/python2.6/site-packages/dpkt', '/usr/lib64/python26.zip', '/usr/lib64/python2.6', '/usr/lib64/python2.6/plat-linux2', '/usr/lib64/python2.6/lib-tk', '/usr/lib64/python2.6/lib-old', '/usr/lib64/python2.6/lib-dynload', '/usr/lib64/python2.6/site-packages', '/usr/lib/python2.6/site-packages']
>>> import dpkt
>>> import icmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "icmp.py", line 6, in <module>
    import ip
  File "ip.py", line 313, in <module>
    __load_protos()
  File "ip.py", line 308, in __load_protos
    IP.set_proto(v, getattr(mod, name.upper()))
AttributeError: 'module' object has no attribute 'ICMP'
>>> import ip
>>>
why?
I have been debugging for a long time,that not solved.

**Comment by brifordwylie** [comment]
I'm assuming this is no longer an issue, closing. We can reopen if needed.
