### ISSUE TITLE
SMB class doesn't reflect actual SMB headers

### ISSUE THREAD

**Issue by danelkay** [kbandla/dpkt#225]
The SMB class in smb.py doesn't seem to reflect the SMB header as described in multiple resources (e.g. [MSDN](https://msdn.microsoft.com/en-us/library/ee441774.aspx), [CodeFX](http://www.codefx.com/CIFS_Explained.htm#_Toc525982093)) and as seen in network traffic captures (e.g. [Wireshark samples](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=smbtorture.cap.gz)).

According to MSDN:
```
The SMB_Header structure is a fixed 32-bytes in length.
 SMB_Header
   {
   UCHAR  Protocol[4];
   UCHAR  Command;
   SMB_ERROR Status;
   UCHAR  Flags;
   USHORT Flags2;
   USHORT PIDHigh;
   UCHAR  SecurityFeatures[8];
   USHORT Reserved;
   USHORT TID;
   USHORT PIDLow;
   USHORT UID;
   USHORT MID;
   }
```

Yet the header defined in smb.py is only 25-bytes in length, and flags2, for example, is erroneously defined as being one byte in length.

The class is currently defined as follows:
```
class SMB(dpkt.Packet):
    __hdr__ = [
        ('proto', '4s', ''),
        ('cmd', 'B', 0),
        ('err', 'I', 0),
        ('flags1', 'B', 0),
        ('flags2', 'B', 0),
        ('pad', '6s', ''),
        ('tid', 'H', 0),
        ('pid', 'H', 0),
        ('uid', 'H', 0),
        ('mid', 'H', 0)
    ]
```

Perhaps this would better reflect the protocol:
```
class SMB(dpkt.Packet):
    __hdr__ = [
    ('proto', '4s', ''),
    ('cmd', 'B', 0),
    ('err', 'I', 0),
    ('flags1', 'B', 0),
    ('flags2', 'H', 0),
    ('pidh', 'H', 0),
    ('signature', '8s', 0),
    ('reserved', 'H', 0),
    ('tid', 'H', 0),
    ('pid', 'H', 0),
    ('uid', 'H', 0),
    ('mid', 'H', 0)
    ]
```

**Comment by brifordwylie** [comment]
@danelkay in general the dpkt project welcomes PRs :) See https://dpkt.readthedocs.org/en/latest/contributing.html for details.
