### ISSUE TITLE
Stop pypcap from capturing and writing network traffic to a file

### ISSUE THREAD

**Issue by mbudge** [kbandla/dpkt#226]
I'm capturing network traffic with pypcap and writing it to a file with dpkt. Problem is I can't delete the file as I get an error saying it's still in use by another process. 

    seconds = 15
    starttime = datetime.datetime.now()

    pc = pcap.pcap()
    file = open('file.pcap', 'wb')
    pcapfile = dpkt.pcap.Writer(file)

    for timestamp, packet in pc:
        currenttime = datetime.datetime.now()
        timedelta = currenttime - starttime
        if timedelta.seconds > seconds:
            break

        pcapfile.writepkt(packet,timestamp)
    pcapfile.close()
    file.close()

    time.sleep(10)

    os.remove(file.pcap) = file in use by another process error

I'm currently overwriting the pcap file the next time I capture traffic. Doing this overwrites the file data most of the time, but occasionally it doesn't work and I end up with a large pcap file encompassing two sets of network capture data.  

How do you close the pcapy/dpkt process handle?

Also does anyone know a better way to stop pcapy capturing traffic after 15 seconds?

Thanks

**Comment by brifordwylie** [comment]
@mbudge so I've tried to reproduce this but cannot. Obviously the code above doesn't actually run as is (probably you've pulled pieces of code from your project). Can you provide a working example? I've tried to guess what you might want with this code:
```python
import os
import datetime
import pcap
import dpkt
import time
seconds = 1 
starttime = datetime.datetime.now()

while 1:
    print 'Opening interface...'
    pc = pcap.pcap(promisc=True, immediate=True)
    print 'Opening pcap file...'
    pcap_file = open('file.pcap', 'wb')
    writer = dpkt.pcap.Writer(pcap_file)
    for timestamp, packet in pc: 
        currenttime = datetime.datetime.now()
        timedelta = currenttime - starttime
        print '\tWriting packet...'
        writer.writepkt(packet,timestamp)

        # Rotate files
        if timedelta.seconds > seconds:
            starttime = datetime.datetime.now()
            print 'Removing pcap file...'
            writer.close()
            pcap_file.close()
            os.remove('file.pcap') 
            print 'Creating pcap file...'
            pcap_file = open('file.pcap', 'wb')
            writer = dpkt.pcap.Writer(pcap_file)
```
This code runs just fine...
```

(chains)Barf:~/tmp$ python pypcap_test.py 
Opening interface...
Opening pcap file...
	Writing packet...
	Writing packet...
...
Removing pcap file...
Creating pcap file...
	Writing packet...
	Writing packet...

```

So anyway maybe the code above will help.. if not provide a full script to reproduce the error and we can dig further.. also may @hellais has some suggestions...

**Comment by brifordwylie** [comment]
question answered... closing
