### ISSUE TITLE
Landscape Errors

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#228]
https://landscape.io/github/kbandla/dpkt/204/messages/error

So I know that code check errors can be spurious but all of these look like they need to be fixed.

**Comment by obormot** [comment]
Unfortunately these kinds of errors happen a lot with dpkt due to its magic way of defining class attributes. E.g. the 1st error, cdp.sum is unknown, it is defined in __hdr__:
```
27: class CDP(dpkt.Packet):
28:	    __hdr__ = (
29:	        ('version', 'B', 2),
30:	        ('ttl', 'B', 180),
31:	        ('sum', 'H', 0)
32:	    )
```

**Comment by kbandla** [comment]
yup, this is not really an issue ( #15)
