### ISSUE TITLE
pcap.py: DLT_RAW constant value

### ISSUE THREAD

**Issue by WGH-** [kbandla/dpkt#229]
Why DLT_RAW is defined to be 14 or 12? In my experience of running tcpdump on tun-interface, it produced pcap files containing just IPv4 packets (i.e. no Ethernet or other kind of encapsulation) with datalink type of 101 (0x65), which was consistent with tcpdump.org definition of DLT_RAW (http://www.tcpdump.org/linktypes.html)

**Comment by RemiDesgrange** [comment]
Maybe need to close this ?

**Comment by WGH-** [comment]
Uhm, no, it's not really fixed.

https://github.com/kbandla/dpkt/blob/c1450e2a6c81a9ff8e82776f91b2b1763cd814bf/dpkt/pcap.py#L128 - these lines are still there, and they override the definitions above.

**Comment by grumple-higi** [comment]
Yeah I just ran into this today, curious why this was closed as DLT_RAW is defined as 101 which is what I have found it to be in almost all files, yet it get's overridden to either 12 or 14 after all the definitions.  So I have to compare against 101 to get the functionality working vs using a constant.
