### ISSUE TITLE
Using dpkt to send raw packet on Mac OSX

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#231]
My googling/SO searching is failing me :)

    # Get info about the machine running this code
    iface_name = net_utils.get_default_interface()
    local_ip = net_utils.get_ip_address(iface_name)
    local_mac = net_utils.get_mac_address(iface_name)
    local_bcast = net_utils.get_broadcast_address(iface_name)

    # Construct the ARP broadcast packet
    arp = dpkt.arp.ARP()
    arp.sha = net_utils.str_to_mac(local_mac)
    arp.spa = net_utils.str_to_inet(local_ip)
    arp.tha = net_utils.str_to_mac('00:00:00:00:00:00') # Target MAC (broadcast)
    arp.tpa = net_utils.str_to_inet('192.168.1.8') # Target IP (broadcast)
    arp.op = dpkt.arp.ARP_OP_REQUEST

    eth = dpkt.ethernet.Ethernet()
    eth.src = arp.sha
    eth.dst = net_utils.str_to_mac('ff:ff:ff:ff:ff:ff')
    eth.type = dpkt.ethernet.ETH_TYPE_ARP
    eth.data = arp

    # Create a raw socket
    print 'ARP Broadcast Packet:'
    print '\t- %s' % local_bcast
    print '\t- %s' % iface_name
    s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_IP)     

    # also tried these for last arg to socket: socket.IPPROTO_RAW, socket.SOCK_RAW, dpkt.ethernet.ETH_TYPE_ARP)

    # Tried lots of different combinations here (yes bind makes no sense but lots of examples had bind)
    s.bind(('', 0))
    s.setsockopt(socket.IPPROTO_IP, socket.IP_HDRINCL, 0) #no headers
    #s.bind((iface_name, socket.SOCK_RAW))
    #s.connect((local_bcast, 1))
    sent = s.sendto(str(eth), (local_bcast,0))
    #sent = s.send(str(eth))
    print sent
    print repr(eth)

I'm getting nothing coming over on my monitoring scripts or wireshark... Here's the printed output from the script:

    Ethernet(src='l@\x08\x89\xfc\x08', dst='\xff\xff\xff\xff\xff\xff', type=2054, data=ARP(spa='\xc0\xa8\x01\t', tpa='\xc0\xa8\x01\x08', sha='l@\x08\x89\xfc\x08', tha='\x00\x00\x00\x00\x00\x00'))

This issue (https://github.com/philsmd/vap11g/issues/3) seems to be at least partially related and looking at the commit referenced at the bottom of the issue... they threw a LOT of code to work around this on Mac.. I'm hoping for my use case it's just a flag/pilot error/quick fix...

Any guidance, suggestions, pointers are greatly appreciated.

**Comment by obormot** [comment]
Scapy sendp() function sends raw packets and works on Mac. I think it uses libdnet, not sure..

**Comment by kbandla** [comment]
`SOCK_RAW` on OS X is a pita. There are a few ways to get around it, as far as packet injection is concerned. 

## Quick hack
In the above case, the most simple way to send a packet is to use `os.write` on the fd returned by the `socket` object:
```
# assume 'packet' is the raw payload
s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_IP)
s.connect((local_bcast,0))
os.write(s.fileno(), packet)
```

## pcap_sendpacket or pcap_inject
Another way to send/inject raw packets. There are many python pcap wrappers out there which you can use to do this. I am using [pypcap](https://github.com/kbandla/pypcap) library in the example below. 
```
# assume 'packet' is the raw payload
x = pcap()
x.pcap_create('en2') # network interface on your OS X instance
x.pcap_activate()
ret = x.pcap_sendpacket(packet)
print ret
```

**Comment by brifordwylie** [comment]
@kbandla @obormot thanks for the feedback, I was trying to limit my dependencies.. but as @kbandla suggested pypcap is easy and my code works with the two lines below... BTW I worked on https://github.com/pynetwork/pypcap a bit.. also updated the pypi distro.

     x = pcap.pcap(name=iface_name)
    ret = x.sendpacket(str(eth))

I'll close this issue.
