### ISSUE TITLE
write the output of python directly in csv format

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#233]
here is my code:
import dpkt
from dpkt.ip import IP
from dpkt.ethernet import Ethernet

import struct
import socket
def ip2int(addr):
    return structs.unpack("!I", socket.inet_aton(addr))[0]
f = open('sample.pcap', 'rb')
pcap = dpkt.pcap.Reader(f)
for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    if eth.type != dpkt.ethernet.ETH_TYPE_IP:
        continue
    ip = eth.data
    do_not_fragment = bool(dpkt.ip.IP_DF)
    more_fragments = bool(dpkt.ip.IP_MF)
    fragment_offset = bool(dpkt.ip.IP_OFFMASK)
    print 'IP: %s -> %s   (len=%d ttl=%d DF=%d MF=%d offset=%d)\n' % \
          (ip.src, ip.dst, ip.len, ip.ttl, do_not_fragment, more_fragments, fragment_offset)

and i want to print the output of this code directly into csv
as am a beginer so not getting how to edit this code so that it directly converted into the csv file

if someone can help then pls reply

you can test this code by inputting any pcap file

**Comment by sheenawadhwa** [comment]
can someone please reply

**Comment by saylenty** [comment]
@sheenawadhwa, There are only a few people who want solve someone's tasks and write the code from the very beginning till the very end. The vast majority of devs prefer interesting non-trivial tasks, however your task seems not to be interesting.
<b>Maybe you've encountered an issue while doing this job or you can't understand the algorithm?</b>
If I were you, I'd start from learning the structure of [CSV](https://en.wikipedia.org/wiki/Comma-separated_values), and how to work with files in python ([in you case](https://docs.python.org/2/tutorial/inputoutput.html)).
Let us know if any help is needed.

**Comment by jonjonLynch** [comment]
I am not sure if you've already figured this out but I can provide an example. I won't re-write your code but but here is a version I had lying around that will give you the idea.
		
	`with open(HTTPOutputFilename, 'wb') as csvfile:
		fieldnames = ['Dest IP', 'HTTP Request Method', 'Host', 'URI']
		parsewriter = csv.DictWriter(csvfile, fieldnames=fieldnames)
		parsewriter.writeheader()
	
		for x in file_list:
			f = open(x) 
			pcap = dpkt.pcap.Reader(f)
			
			for ts, buf in pcap:
				eth = dpkt.ethernet.Ethernet(buf)
				ip = eth.data
				tcp = ip.data
				
				try:
					if tcp.dport == 80:
						http = dpkt.http.Request(tcp.data)
						dst_ip_addr_str = socket.inet_ntoa(ip.dst)
						parsewriter.writerow({'Dest IP': dst_ip_addr_str, 'HTTP Request Method': http.method, 'Host': http.headers['host'], 'URI': http.uri})
				except:
					continue`

**Comment by sheenawadhwa** [comment]
my code is working fine but the issue is, it is printing only 1st packet
output in csv file.
well am not getting how to use the loop here so that it can print all the
present value in csv

here is my code:

import dpkt
from dpkt.ip import IP
from dpkt.ethernet import Ethernet
import struct
import socket
import csv
def ip_to_str(address):
    return socket.inet_ntoa(address)
f = open('sample.pcap', 'rb')
pcap = dpkt.pcap.Reader(f)
for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    if eth.type != dpkt.ethernet.ETH_TYPE_IP:
        continue
    ip = eth.data
    do_not_fragment = bool(dpkt.ip.IP_DF)
    more_fragments = bool(dpkt.ip.IP_MF)
    fragment_offset = bool(dpkt.ip.IP_OFFMASK)
    c = csv.writer(open("a.csv", "wb"))
    Source = "%s" % ip_to_str(ip.src)
    Destination = "%s" % ip_to_str(ip.dst)
    Length = "%d" % (ip.len)
    TTL = "%d" % (ip.ttl)
    DF = "%d" % (do_not_fragment)
    MF = "%d" % (more_fragments)
    FO = "%d" % (fragment_offset)
    for row in f:
        data = (Source, Destination, Length, TTL, DF, MF, FO)
    c.writerow(data)

**Comment by sheenawadhwa** [comment]
please remove "for row in f:" before testing my code
for row in f:
        data = (Source, Destination, Length, TTL, DF, MF, FO)
    c.writerow(data)

**Comment by sheenawadhwa** [comment]
please someone help to find the issue

**Comment by kbandla** [comment]
The issue occurs because you create a new csv instance *everytime* inside the for loop that processes. Moving that out of the loop will solve your issue. Secondly, im not sure why you are trying to loop before you write the row is not needed. 
```
for row in data:
        c.writerow(data)
```
I have fixed these *for* you [here](https://gist.github.com/kbandla/baf7ca47429fd6c53696). (I did not test it).If this solved your issue, please go ahead and close the ticket. 

Please note that this is the issue ticketing system for the dpkt project, and not a place for python programming questions. Please post them on programming forums like Stackoverflow the next time.
