### ISSUE TITLE
output of table is not in a format as required

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#234]
here is my code:
import dpkt
from dpkt.ip import IP
from dpkt.ethernet import Ethernet
from tabulate import tabulate
import struct
import socket
def ip_to_str(address):
    return socket.inet_ntoa(address)
f = open('sample.pcap', 'rb')
pcap = dpkt.pcap.Reader(f)
for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    if eth.type != dpkt.ethernet.ETH_TYPE_IP:
        continue
    ip = eth.data
    do_not_fragment = bool(dpkt.ip.IP_DF)
    more_fragments = bool(dpkt.ip.IP_MF)
    fragment_offset = bool(dpkt.ip.IP_OFFMASK)
    table = ['%s %s %d %d %d %d %d)' %
    (ip_to_str(ip.src), ip_to_str(ip.dst), ip.len, ip.ttl, do_not_fragment, more_fragments, fragment_offset)]
    headers = ["Source", "Destination", "Length", "TTl", "DF", "MF", "FO"]
    print tabulate(table,headers, tablefmt="plain")

whose output is coming like this:

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
======================= RESTART: C:\Python27\table.py =======================
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   6       1   7   2  .    1   6  .    1  .    1   1   9       8   9       6   4                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   9       1   7   2  .    1   6  .    1  .    1   1   6       8   4       6   0                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   9       1   7   2  .    1   6  .    1  .    1   1   6       8   7       6   0                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   6       1   7   2  .    1   6  .    1  .    1   1   9       4   7       6   4                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   6       1   7   2  .    1   6  .    1  .    1   1   9       8   9       6   4                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   9       1   7   2  .    1   6  .    1  .    1   1   6       8   4       6   0                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   6       1   7   2  .    1   6  .    1  .    1   1   9       8   9       6   4                        1                1           1  )
                                                                                                                            Source      Destination  Length      TTl  DF      MF  FO
 1   7   2  .    1   6  .    1  .    1   1   9       1   7   2  .    1   6  .    1  .    1   1   6       8   4       6   0                        1                1           1  )
>>> 

where required output is headers should be printed only once in a row and values should be low that 
Source                   Destination            Length       TTL       DF MF FO
172.16.1.116         172.16.1.119            89             64         1    1    1
.........so on 
but my output is so messy i am not getting where am doing wrong

could someone please help

**Comment by saylenty** [comment]
@sheenawadhwa, you code is not readable, please have a look at the [doc](https://guides.github.com/features/mastering-markdown/) -> section "Code".
About your issue - that happens because your code:

    print tabulate(table,headers, tablefmt="plain")

is executed in a loop:

    for ts, buf in pcap:

That's why you print all the headers again and again.
Good luck.

**Comment by sheenawadhwa** [comment]
thanks :)
