### ISSUE TITLE
Wireshark parses Ericsson Research dataset, but DPKT does not. 

### ISSUE THREAD

**Issue by josvr** [kbandla/dpkt#235]
Hi,

I have a problem with parsing a pcap file with DPKT, which parses correctly using wireshark.

Reproduction details:

get 700 MB Source tar:   wget http://www.crysys.hu/~szabog/measurement.tar

This is the normal network dataset created by the Traffic Laboratory of Ericsson Research which parses fine with Wireshark:

If I run on untarred PCAP:

    f = open('measurement.pcap', 'rb') 
    pcap = dpkt.pcap.Reader(f)

    for ts, buf in pcap:
            eth = dpkt.ethernet.Ethernet(buf)
            print 'eth type %d python datatype %s '%(eth.type,type(eth.data))

I get:

    eth type 44048 python datatype <type 'str'> 
    eth type 54544 python datatype <type 'str'> 

Does someone have any idea what the issue is?

Version:

    pip show dpkt
    ---
    Metadata-Version: 2.0
    Name: dpkt
    Version: 1.8.6.2

**Comment by kleptog** [comment]
I downloaded the PCAP and opened it in wireshark myself. This file doesn't contain ethernet packets but IP packets. So you need to decode with dpkg.ip.IP.

You could have seen this by checking pcap.datalink() == DLT_RAW.

**Comment by brifordwylie** [comment]
Elaborating on @kleptog comment if you put in some logic for the datalink type it will work (I tried this on your pcap and worked fine).

```
import dpkt
import socket

def inet_to_str(inet):
    """Convert inet object to a string

        Args:
            inet (inet struct): inet network address
        Returns:
            str: Printable/readable IP address
    """
    # First try ipv4 and then ipv6
    try:
        return socket.inet_ntop(socket.AF_INET, inet)
    except ValueError:
        return socket.inet_ntop(socket.AF_INET6, inet)

# Open the PCAP fle
f = open('measurement.pcap', 'rb') 
pcap = dpkt.pcap.Reader(f)
datalink = pcap.datalink() 
print 'PCAP DataLink: %s' % datalink 

for ts, buf in pcap:
    if datalink == dpkt.pcap.DLT_EN10MB:
        eth = dpkt.ethernet.Ethernet(buf)
        ip = eth.data
    elif datalink == 101: # dpkt.pcap.DLT_RAW == 12 on my Mac
        ip = dpkt.ip.IP(buf)
    print '{:s} --> {:s} len:{:d} ttl{:d}'.format(inet_to_str(ip.src), inet_to_str(ip.dst), ip.len, ip.ttl)
```

So take this code and have fun... we'll close this issue now.
