### ISSUE TITLE
possible decoding DHCP Giaddr, Yiaddr, Ciaddr, siaddr field issue 

### ISSUE THREAD

**Issue by manojcode** [kbandla/dpkt#244]
Hi,

Thanks for great library.

but whenever I try to load Giaddr (or YIADDR Ciaddr, siaddr ) for any DHCP packet it **prints random string of numbers**. ( this happens for each n every packet I load)

Am I doing something wrong or it's a bug in code? 

code 
```
dh = dpkt.dhcp.DHCP(udp.data)
print dh.giaddr
```

**output : 
182435815**

I am pretty sure that my **giaddr(relay ip)** is **10.223.191.231** - confirmed in wireshark for this packet.

**Comment by kbandla** [comment]
Could you share the pcap @manojcode? Would be easier to debug with it

**Comment by RemiDesgrange** [comment]
182435815 is the same thing that 10.223.191.231
ip to decimal :
`(10 << 24) + (223 << 16) + (191 << 8) + 231`

decimal to ip (not optimized at all)
```python
dec_val = 182435815
mask = pow(2,24)
ip = list()
for x in range(4):
    ip.append(dec_val/mask)
    dec_val -= (dec_val/mask)*mask
    mask /= 256
print '.'.join(str(x) for x in ip)
```

**Comment by kbandla** [comment]
@manojcode your output is correct. You have a the integer value of the address.
```
>>> import struct
>>> socket.inet_ntoa(struct.pack(">L",x))
'10.223.191.231'
```

**Comment by manojcode** [comment]
Thanks Remi, Kbandla for looking into it so fast. 

Both the solutions work like a charm. Appreciate your help :)
