### ISSUE TITLE
how to print payload information along each packet of pcap

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#246]
i am not getting how to print the payload information with each packet of pcap during parsing

**Comment by kbandla** [comment]
This is a very open question. It really depends on the type of packet you are trying to process. 
However, if just printing the payload is all you want, then a simple `.data` property of the packet type will print the corresponding data. See the [examples](https://dpkt.readthedocs.org/en/latest/examples.html)
