### ISSUE TITLE
distinguish a packet whether its normal or attack

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#247]
how to identify  that packet in a pcap file is a normal or attack. so that when the pcap file is getting parsed it prints with each single packet i.e. normal / attack by identify

**Comment by kbandla** [comment]
This is an extremely open-ended question. I am going to assume this is in relation with the other pcaps you posted, which has malformed ICMP traffic. 

Here is a very hacky way to get what you want:
```
for ts, buf in pcap:
    ip = dpkt.ip.IP(buf)
    print ip_to_str(ip.src), ip_to_str(ip.dst)
    if ip.p == dpkt.ip.IP_PROTO_ICMP:
        try:
            icmp = dpkt.icmp.ICMP(ip.data)
            # normal packet
        except Exception as e:
            # malformed icmp packet
            print 'Malformed'
```
