### ISSUE TITLE
Print IP is not working for Caida dataset

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#248]
my code is working well with all sample files of pcap but its not working for  caida dataset. am not able to resolve this issue from last one month. my project is stuck only due to this issue.

I am using Python 27 on Windows OS
Sample captures ["https://wiki.wireshark.org/SampleCaptures"]
Caida dataset ["https://drive.google.com/file/d/0BwwWAQYvet7Eb0JNRFdlTHlQUGc/view?usp=sharing"]

import dpkt

from dpkt.ip import IP

from dpkt.ethernet import Ethernet

import struct

import socket

import csv

def ip_to_str(address):

    return socket.inet_aton(address)

f = open('ddostrace.20070804_140436.pcap', 'rb')

pcap = dpkt.pcap.Reader(f)

print "Source, Destination, Length, TTL, TOS, OFF, Protocol, Label"

for ts, buf in pcap:

    eth = dpkt.ethernet.Ethernet(buf)

    if eth.type != dpkt.ethernet.ETH_TYPE_IP:

        continue

    ip = eth.data

    do_not_fragment = bool(dpkt.ip.IP_DF)

    more_fragments = bool(dpkt.ip.IP_MF)

    fragment_offset = bool(dpkt.ip.IP_OFFMASK)

    Source = "%s" % ip_to_str(ip.src)

    Destination = "%s" % ip_to_str(ip.dst)

    Length = "%d" % (ip.len)

    TTL = "%d" % (ip.ttl)

    OFF = ip.off

    TOS = ip.tos

    Protocol = ip.p

    Label = 'Attack / Normal'

    print Source, Destination, Length, TTL, TOS, OFF, Protocol, Label

**Comment by RemiDesgrange** [comment]
your spamming in the morning men...

Could you:
-put your code in a code section
-describe your setup (python version, OS)
-are you sure your pcap file is a well formated pcap file ?
-what is the actual error !!

**Comment by sheenawadhwa** [comment]
yes my pcap file is well formatted you can check it in Wireshark tool. And it displays no error just print command is not working for caida but its working for all other sample captures.. the link is given in question

**Comment by RemiDesgrange** [comment]
Found it !! there is no Ethernet layer in your pcap ;-)

**Comment by sheenawadhwa** [comment]
but i have code for printing ethernet fields thats working fine  for caida

**Comment by RemiDesgrange** [comment]
Look at your capture file in wireshark, there is no layer 2 in your pcap
file

**Comment by sheenawadhwa** [comment]
so that means there is issue of pcap file not of my code :)

**Comment by RemiDesgrange** [comment]
That's means that your code assume the first layer present in the pcap is
Ethernet, in this case, it's not true.

**Comment by sheenawadhwa** [comment]
is there any other way to print ips of this dataset

**Comment by RemiDesgrange** [comment]
Yes by replacing `eth = dpkt.ethernet.Ethernet(buf)` by this `ip = dpkt.ip.IP(buf)`

**Comment by sheenawadhwa** [comment]
thanks alot it worked well

**Comment by sheenawadhwa** [comment]
@RemiDesgrange am facing same issue for TCP print .. can u help

**Comment by sheenawadhwa** [comment]
for ts, buf in pcap:

    eth = dpkt.ethernet.Ethernet(buf)

    if eth.type != dpkt.ethernet.ETH_TYPE_IP:

        continue

    ip = eth.data

    tcp = ip.data

    Src = tcp.sport

    Dstport = tcp.dport

    print  Src, Dstport

**Comment by RemiDesgrange** [comment]
do you have any idea of what you are doing here ? :-) 

seriously, if it's the same capture than the last time, you don't have any tcp in there, it's just ICMP...

```python
with open(sys.argv[1]) as f:
    pcapFile = pcap.Reader(f)
    decoder = None
    if pcapFile.datalink() == pcap.DLT_EN10MB:
        print("loading pcap with ethernet layer")
        decoder = ethernet.Ethernet
    elif pcapFile.datalink() == pcap.DLT_IEEE802_11:
        print("loading pcap with wifi layer")
        decoder = ieee80211.IEEE80211
    elif pcapFile.datalink() == pcap.DLT_NULL:
        decoder = loopback.Loopback
    else:
        print('unknown layer : {}, not decoding '.format(pcapFile.datalink()))
        exit(-1)
for ts, buf in pcapFile:
    layer2 = decoder(buf)
    if type(layer2.data) == ethernet.Ethernet:
        layer2 = ethernet.Ethernet(layer2.data)
    if type(layer2.data) == ip.IP:
        layer3 = layer2.data
        if layer3.p == ip.IP_PROTO_TCP:
            dst_port, src_port = parseTcp(layer3.data)
        elif layer3.p == ip.IP_PROTO_UDP:
            dst_port, src_port = parseUdp(layer3.data)
        else:
            unknownLayer4.add(layer3.p)
    elif type(layer2.data) == ip6.IP6:
        layer3 = layer2.data
        if layer3.nxt == ip.IP_PROTO_TCP:
            dst_port, src_port = parseTcp(layer3.data)
        elif layer3.nxt == ip.IP_PROTO_UDP:
            dst_port, src_port = parseUdp(layer3.data)
        else:
            unknownLayer4.add(layer3.nxt)
    elif type(layer2.data) == arp.ARP:
        layer3 = layer2.data
        nb_arp +=1
    else:
        unknownLayer3.add(type(layer2.data))
```

This code is way incomplete and I copy paste from a sample, so I don't know if it's working but it gives you an idea

**Comment by kbandla** [comment]
@sheenawadhwa The bulk of your pcap is made of malformed ICMP packets, encapsulated inside rawIP frames. Parse them accordingly, as @RemiDesgrange pointed
