### ISSUE TITLE
Print TCP is not working for caida

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#249]
my code is working well with all sample files of pcap but its not working for  caida dataset. am not able to resolve this issue from last one month.As Ethernet layer is not present in my required caida pcap file so is there any issue to resolve this than any help will be appriciated.
I am using Python 27 on Windows OS
Sample captures ["https://wiki.wireshark.org/SampleCaptures"]
Caida dataset ["https://drive.google.com/file/d/0BwwWAQYvet7Eb0JNRFdlTHlQUGc/view?usp=sharing"]

import dpkt

from dpkt.ip import IP

from dpkt.ethernet import Ethernet

from dpkt.tcp import TCP

import struct

import socket

import csv

def ip_to_str(address):

    return socket.inet_ntoa(address)

f = open('sample.pcap', 'rb')

pcap = dpkt.pcap.Reader(f)

print "ACK, SYN, FIN, Conn, Srcport, Dstport, sum"

for ts, buf in pcap:

    eth = dpkt.ethernet.Ethernet(buf)

    if eth.type != dpkt.ethernet.ETH_TYPE_IP:

        continue

    ip = eth.data

    tcp = ip.data

    ACK = dpkt.tcp.TH_ACK

    SYN = dpkt.tcp.TH_SYN

    FIN = dpkt.tcp.TH_FIN

    Connection = dpkt.tcp.TCP_OPT_CC

    Src = tcp.sport

    Dstport = tcp.dport

    sum = tcp.sum

    print ACK, SYN, FIN, Connection, Src, Dstport, sum

**Comment by kbandla** [comment]
This is not a bug

**Comment by kbandla** [comment]
@sheenawadhwa, the pcap's Encapsulation type is NOT Ethernet, as you expect in your code:
```
for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    ...
```
In this case, the Encapsulation type is Raw IP, and not Ethernet. Easiest way you can find this is using a tool like Wireshark. 
Secondly, bulk of the pcap seems to have ICMP packets, whereas your code is looking for TCP packets. You will have to rewrite your code accordingly. 

You can read the Raw IP frames by directly parsing them as IP: 
```
for ts, buf in pcap:
    ip = dpkt.ip.IP(buf)
    print ip_to_str(ip.src), ip_to_str(ip.dst)
    ...
```
The ip proto is 1 (ICMP). However, you notice that the ip payload (icmp) is only 8 bytes, which is shorter than the standard icmp packet.
