### ISSUE TITLE
how can i count number of packets from same source, destination based on sport and dport from csv or pcap file

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#252]
I'm trying to code a program which prints the output consists of same IP's contains x number of packets based on port number using dpkt.I want the output like:

from 10.1.1.1 to 10.1.1.2 on port 52 contains 28 packets

from 10.1.2.1 to 10.1.2.2 on port 80 contains 50 packets

...

I hope you understand what I really want, I am not getting how to do this. Any help will be appreciated.

**Comment by RemiDesgrange** [comment]
You have multiple ways of doing it. Since IP doesn't have any port information (layer 4 have, like TCP, UDP). 

you could just create a class "stream" or "flow", that take on argument : `ip_src, ip_dst, port_src, port_dst, proto` and then check that correponding argument fits. Be aware that in a flow, `this_packet.ip_src` == next_packet.ip_dst`

**Comment by sheenawadhwa** [comment]
okay but am new to python so am little bit confuse. In actuall i wants the field like the following.. can you provide me the code so that i can modify according to my following requirements with same ips and ports

src               	dst	                      pro	 sport	dport	pkts	      bytes	     flows

189.78.92.2	192.168.10.10   	6	 55167	80	         8              745	         1

192.168.10.10	 33.33.34.1	        6	   80	      37502	11           12363	  1

**Comment by RemiDesgrange** [comment]
This is not about Python, the algorithms will be the same in every
language, maybe a good start will be to read some theories about TCP/IP
stack. Try something, post it here and we will correct you if it is
fundamentally wrong. It's way harder. By in the end you will have learn a
lot.

**Comment by sheenawadhwa** [comment]
there's netflow.py is present in dpkt package but am not able to use this as ip tcp can be used like
print ip.src, tcp.sport
how can i use this netflow's vairiable like count, uptime etc
