### ISSUE TITLE
How to use Netflow.py from dpkt

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#253]
i want to fetch the fields of netflow but am not able to use. As ip.py we fetch by 

print ip.src

so how to use netflow.??

**Comment by kbandla** [comment]
Based on @sheenawadhwa other open tickets, I am assuming that you are trying to create netflows from a pcap. 
`netflow.py` is used to parse Cisco's netflow packets. It is NOT for creating netflows from a pcap.

**Comment by sheenawadhwa** [comment]
okay but i want to display flows for ipv4 then how can i do that?

**Comment by kbandla** [comment]
> okay but i want to display flows for ipv4 then how can i do that?

First, you need to familiarize yourself with Netflow. You can find many resources online, a simple Google should help you. You can use existing tools to create netflows from a packet capture file like [softflowd](https://code.google.com/archive/p/softflowd/) or others. 

I do not have code lying around that does netflow in dpkt. We will hopefully add code to the library to do this, but it is out of scope for this issue.
