### ISSUE TITLE
Count the number of packets on source and destination occured on each same sport and dport

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#254]
I want the output like following everything is done except am not able to count the pkt field which counts packets on the occurence of same sport and dport  and also flow id is not able to use. I ve searched alot but not able use these methods

src	dst	pro		sport	dport	pkts	bytes	flows

189.78.92.2	192.168.10.10	6	55167	80	8	745	1	

192.168.10.10	33.33.34.1	6	80	37502	11	12363	1

189.78.92.2	192.168.10.10	6	55165	80	10	905	1

**Comment by sheenawadhwa** [comment]
anyone can ans this 
my project is stuck due to this

**Comment by kbandla** [comment]
Can you post your code on [gist](https://gist.github.com) and share the link here?

**Comment by sheenawadhwa** [comment]
<script src="https://gist.github.com/sheenawadhwa/c4089f0b20fa34aaae34.js"></script>

**Comment by sheenawadhwa** [comment]
https://gist.github.com/sheenawadhwa/c4089f0b20fa34aaae34

**Comment by RemiDesgrange** [comment]
Ok. So you're new to python and that's ok. This is the ways of doing what you did in a more "pythonic" and compatible with both python 2 and 3.

```python
from __future__ import absolute_import, print_function, unicode_literals
import dpkt
import socket
import sys


def ip_to_str(address):
    """
    transform a int ip address to a human readable ip address (ipv4)
    """
    return socket.inet_ntoa(address)


def mac_addr(mac_string):
    """
    transform a int mac address to a human readable mac address (EUI-48)
    """
    return ':'.join('%02x' % ord(b) for b in mac_string)


def compute(cap_file):
    with open(cap_file, 'rb') as f:
        pcap = dpkt.pcap.Reader(f)
        #the datalink type MUST be ethernet
        assert (pcap.datalink() == dpkt.pcap.DLT_EN10MB), "the datalink is not ethernet, aborting"

        for ts, buf in pcap:
            eth = dpkt.ethernet.Ethernet(buf)
            if eth.type == dpkt.ethernet.ETH_TYPE_IP:
                ip = eth.data
                # you have to be aware that this will give you the size of
                # the entire frame. with ethernet addr, ethertype, ip addr
                # etc... not the payload size. For the payload size,
                # you have to do len(tcp.data)
                framesize = len(buf)
                ip_info = '''ip src:{src}, ip dst: {dst},
                protocol: {protocol},
                frame size:{payload},'''.format(
                src=ip_to_str(ip.src),
                dst=ip_to_str(ip.dst),
                protocol=ip.p,
                payload=framesize
                )
                if ip.p == dpkt.ip.IP_PROTO_TCP:
                    tcp = ip.data
                    print('{}, src port:{}, dst port:{}'.format(
                        ip_info,
                        tcp.sport,
                        tcp.dport
                        ))

if __name__ == '__main__':
    try:
        filename = sys.argv[1]
    except:
        filename = 'ipp.pcap'
    compute(filename)
```

And now you want to count this. why not using python list or python set. Or maybe create an object, like, I don't know, 'TcpStream' that does this for you.

**Comment by sheenawadhwa** [comment]
@RemiDesgrange i dint got u. How can i create list beacuse i want to count the packets from each source port to destination port of pcap file. I am not getting how to get the required output

**Comment by sheenawadhwa** [comment]
@RemiDesgrange the fields u tried to fetch from your above code, that fields are already been fetched by me.  Count packets and flow is remaining

**Comment by kbandla** [comment]
This is getting a little out of hand.
@sheenawadhwa : The code you shared is exactly what you were helped out in #232 . There is not a single line of additional code. Sites like [stackoverflow](http://stackoverflow.com) are the right places for questions like this. 

[Here](https://gist.github.com/48e6e9fb855103551195) is your fish.
