### ISSUE TITLE
Add support for PPI

### ISSUE THREAD

**Issue by RemiDesgrange** [kbandla/dpkt#256]
Hi,

I would add support for PPI, do you think it worth it ?

spec : 
https://www.cacetech.com/documents/PPI%20Header%20format%201.0.7.pdf
sample :
https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=Http.cap

**Comment by kbandla** [comment]
There is an older ticket #72 which was about this too. 
We can surely add/cleanup existing 802.11 related stuff. If you are working on it anyway, go for it man!

**Comment by RemiDesgrange** [comment]
BTW, PPI is not only for wifi ;-)

**Comment by kbandla** [comment]
even better!

**Comment by RemiDesgrange** [comment]
Don't have the time sorry, closing it
