### ISSUE TITLE
print source byte and destination byte and duration

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#260]
i want to print connection record fields which also contains feilds like Src_byte and Dst_byte and duration. The simple method is to display bytes and timestamp is 

for ts, buf in pcap:

print len(buf), ts

but am not getting how to print src_byte and dst_byte separately and count duration for each packet of pcap

**Comment by rdesgrange-lf** [comment]
Ok, so imagine that you have the @kbandla gracioucly gave you about flow. In flow you can easily put a count for `src_bytes` and `dst_bytes`.

But I want to be sure that we are talking about the same thing about `src_bytes` and `dst_bytes`. If A and B have a discussion. You want to log bytes from A->B and bytes from B->A ? right

**Comment by sheenawadhwa** [comment]
i Don't want to add these fields in flow info as this is somehow different code just not getting how to count total bytes on wire i.e. source byte and bytes captured i.e destination bytes and yes like A to B and B to A

**Comment by rdesgrange-lf** [comment]
Ok so I don't understand what you meant then. I am giving up here

**Comment by sheenawadhwa** [comment]
as we can calculate bytes like 

print len(buf) 

it prints the bytes but i want to print separate fields of bytes as wireshark displays
src_byte and dst_byte

**Comment by sheenawadhwa** [comment]
Any one can help!!!

**Comment by RemiDesgrange** [comment]
Can you show us a screenshot of wireshark with this metrics ?

**Comment by sheenawadhwa** [comment]
![capture](https://cloud.githubusercontent.com/assets/16634014/14307297/bda8753c-fb82-11e5-9503-d07342b216ba.PNG)

**Comment by sheenawadhwa** [comment]
as you can see Frame length, Capture length. I want to display same in python and Duration is not present in this snapshot but want to calculate like Duration = Last_ts - First_ts , not getting how to declare these so that it could calculate duration also

**Comment by sheenawadhwa** [comment]
?

**Comment by sheenawadhwa** [comment]
anyone can help because am stuck in this issues from week

**Comment by RemiDesgrange** [comment]
look at that maybe, don't know why you want this, but maybe it can help : https://github.com/kbandla/dpkt/blob/master/dpkt/pcap.py#L140-147

**Comment by sheenawadhwa** [comment]
how i can count DURATION

**Comment by RemiDesgrange** [comment]
Maybe you need computer science 101...

**Comment by sheenawadhwa** [comment]
sorry, i dint get you

**Comment by kbandla** [comment]
not an issue. Closing it
