### ISSUE TITLE
want to create drop down menu

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#261]
i am able to create the drop down menu simply but not able to merge the code with other code.

i want to merge the dropdown menu code with tkinter output.py file so that in output.py file the buttons should be same as in drop down menu. i tried alot but stuck in this issue from 2 weeks. any help will be appriciated

here is the code for drop down menu
https://gist.github.com/sheenawadhwa/a1197057438020af39b0e71cf390b3d0

here is the code that i want to merge with 
https://gist.github.com/sheenawadhwa/93a041c0152a327b04104df06ff6120a

**Comment by kbandla** [comment]
@sheenawadhwa I have never worked with tkinter before. I dont think i can help you here. 
Considering that this is not an "issue" with dpkt, i am going to mark this as wontfix.

**Comment by obormot** [comment]
@sheenawadhwa how is this related to dpkt? the issue is invalid in the context of this project.
