### ISSUE TITLE
Fetch only some fields of selected header of pcap

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#269]
I want to extract only some fields from IP header and convert the selected fields into csv. For example i select the IPv4 header then there should be list of fileds that i can print, then user can select their required fields from the list, at last there will be option of creating csv of that particular selected fields.
I am stuck in this from last 2 weeks. Any help will be appriciated.

**Comment by sheenawadhwa** [comment]
Is there any other solution to my problem that can fulfill my requirement?

**Comment by kbandla** [comment]
The fields in each header can be found in the `__hdr__` attribute for the class. Example: [headers for ipv4](https://github.com/kbandla/dpkt/blob/master/dpkt/ip.py#L10-L20). Hope this helps.
