### ISSUE TITLE
Unexpected Error!! While using dpkt to read pcap file

### ISSUE THREAD

**Issue by MujtabaKhan** [kbandla/dpkt#272]
I'm using dpkt for extracting the fields from a pcap file. 
Can anyone help me to solve the attribute error mentioned below 
The line causing error is also mentioned and error being generated.

code :
f = open('test.pcap')
pc = dpkt.pcap.Reader(f) 

Error:
AttributeError: 'module' object has no attribute 'pcap'

**Comment by obormot** [comment]
You're most likely importing "dpkt" module locally, instead of importing "dpkt" package. If you're inside directory "dpkt" with all the protocol parsers (dns.py, http.py, etc.) it means your import statement picks up dpkt.py locally.

**Comment by MujtabaKhan** [comment]
it because of the following piece of code: 

if __name__ == "__main__":
    main()

As per my understanding

**Comment by obormot** [comment]
@MujtabaKhan do this in your code:
```
import dpkt
print dir(dpkt)
```
and post the output here

**Comment by MujtabaKhan** [comment]
Too Much Error!

['Error', 'NeedData', 'PackError', 'Packet', 'UnpackError', '__author__', '__author_email__', '__builtins__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__url__', '__version__', 'ah', 'aim', 'aoe', 'aoeata', 'aoecfg', 'arp', 'array', 'asn1', 'bgp', 'cdp', 'copy', 'crc32c', 'decorators', 'dhcp', 'diameter', 'dns', 'dpkt', 'dtp', 'esp', 'ethernet', 'gre', 'gzip', 'h225', 'hexdump', 'hsrp', 'http', 'icmp', 'icmp6', 'ieee80211', 'igmp', 'in_cksum', 'in_cksum_add', 'in_cksum_done', 'ip', 'ip6', 'ipx', 'itertools', 'llc', 'loopback', 'mrt', 'netbios', 'netflow', 'ntp', 'ospf', 'pcap', 'pcapng', 'pim', 'pmap', 'ppp', 'pppoe', 'qq', 'radiotap', 'radius', 'rfb', 'rip', 'rpc', 'rtp', 'rx', 'sccp', 'sctp', 'sip', 'sll', 'smb', 'socket', 'ssl', 'ssl_ciphersuites', 'stp', 'struct', 'stun', 'tcp', 'telnet', 'tftp', 'tns', 'tpkt', 'udp', 'vrrp', 'yahoo']

**Comment by obormot** [comment]
Looks correct. You're importing a package in this case. Make sure to do the same in your main code.
