### ISSUE TITLE
TCPDUMP_MAGIC_NANO constant doesn't work

### ISSUE THREAD

**Issue by basvs** [kbandla/dpkt#276]
The TCPDUMP_MAGIC_NANO constant is currently defined as 0xa1b23c4d,
but it should be defined as 0xa1b23c4dL.

Regards,

Bas van Sisseren

**Comment by obormot** [comment]
This might've been addressed with https://github.com/kbandla/dpkt/pull/308
Closing as with Python3 compatibility all "L" suffixes had to be removed. @basvs please reopen if still an issue (and give an example).

**Comment by basvs** [comment]
I had problems reading .pcap files, but I cannot reproduce it anymore.

Simple test-case:
Create pcap-files with each of the 4 magic values.
And read the pcaps with:
  dpkt.pcap.Reader( open("file.pcap", "rb") )

**Comment by obormot** [comment]
Looks like we need a unit test for pcap.Writer. I will add it
