### ISSUE TITLE
Count of the number of packets with the ip address in pcap file

### ISSUE THREAD

**Issue by denzelw2** [kbandla/dpkt#277]
I'm new to python. What is the process of designing a code that counts the number of packets with the same ip address in a pcap file.

**Comment by brifordwylie** [comment]
@denzelw2 if you look at the example on https://dpkt.readthedocs.io/en/latest/examples.html#examples-in-dpkt-examples you can see the code pulling out the fields in the packet including the src and dst ip address. So you can take that example code as a starting point, add a Counter object and simply add up the packets for each unique ip you see.

```
In [1]: from collections import Counter
In [2]: ip_counter = Counter()
In [3]: ip_counter['192.168.0.1'] += 1
In [4]: ip_counter['192.168.0.2'] += 1
In [5]: ip_counter['192.168.0.1'] += 1
In [6]: ip_counter
Out[6]: Counter({'192.168.0.1': 2, '192.168.0.2': 1})
```

That's about as much help as we can give here.. the project is focused on DPKT not python programming in general. Cheers and best of luck!
