### ISSUE TITLE
Deprecate perf tests folder

### ISSUE THREAD

**Issue by egberts** [kbandla/dpkt#278]
When running:
```bash
python test-perf.py
```
I get the following error message:

`   ImportError: No module named xstruct`

Github and Google does not reveal where one can easily find this Python package.  Where can one find this `xstruct` package?

**Comment by kbandla** [comment]
Thanks for pointing this out @egberts 
This is a really old python module from 1999, which is not available anywhere now. The test scripts were written for performance testing against other python packet libraries. We hope to update these scripts, or get rid of them entirely. 

That said, if you _have_ to run them and *need* `xstruct`, I found a copy of it on redhat and added it [here](https://github.com/kbandla/python-xstruct). It did not have a build file, so i added one. However, I have not tested it and it might not even work with the latest Python versions. ymmv.

**Comment by kbandla** [comment]
@brifordwylie @obormot I think we can do away with the tests folder, which contains some performance tests - that rely on multiple legacy python modules. Once that is done, we can close this issue. Updated issue title to reflect this.

**Comment by obormot** [comment]
Sounds good to me
