### ISSUE TITLE
Stackoverflow questions

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#291]
Stackoverflow is a primary resource for many programmers. If they are searching around and see a bunch of dpkt questions with old/doesn't quite work/inadequate answers they may be 'turned off' to dpkt.

So we should take a stab at trying to answer those questions (even old ones) with updated answers that point them to the new docs/code.

**Comment by kbandla** [comment]
@brifordwylie I have been doing this for sometime now. Questions are sporadic, but I do get to them, and point them to the docs where possible. At this point, I have started to see the same sort of questions. I made a list somewhere; hoping to add them to a FAQ section in the docs sometime..

**Comment by brifordwylie** [comment]
@kbandla okay sounds good.. .I answered a few last night..I'll try to do a few more this week. We'll consider this issue 'covered' and I'll close it.

**Comment by abhikeny** [comment]
I like this initiative. Kudos to the dpkt developers/users taking part in doing this. I appreciate this.
