### ISSUE TITLE
Investigate for Memory Leaks

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#300]
While reading [this](https://reproducingnetworkresearch.wordpress.com/2016/05/30/cs244-16-an-accurate-sampling-scheme-for-detecting-syn-flooding-attacks-and-portscans/) article, I noticed that the author talks about a memory leak in dpkt. It seems that they were trying to reproduce [this](http://mkorczynski.com/An%20Accurate%20Sampling%20Scheme%20for%20Detecting%20SYN.pdf) paper's results.

> Unfortunately, after writing most of our code and testing on smaller datasets, we ran it on a larger file and discovered a memory leak in the library. This made it tricky to run our code on very large pcap files, and ended up capping the max number of packets we could process  and analyze to 27 million (on a machine running with 32 GB of RAM). 

They go on to say the following in the feedback section of the paper:

> The main issue was with the memory leak in dpkt. We were able to get around it by just running our code on machines with a lot of memory (Felipe’s laptop has 16GB of RAM, and Keziah spun up an AWS instance with 32 GB of RAM and we stopped having problems). However, if you want to run locally on machines with less memory, I would avoid this library.

Specifically about this issue - I dont yet know where/what leak they found, but I am going to ping them about it. Hopefully we can reproduce & fix this, iff this is a problem with dpkt.

It is easier to blame this on python's internal memory allocator, which does not release memory back to the OS, but lets see. Maybe we can add some code patterns to the examples which could be used as a workaround (for not just dpkt, but for python performance/memory problems in general).  

Update: 
- The dataset is available [here](http://www.caida.org/data/passive/ddos-20070804_dataset.xml)
- The code used in the test is available [here](https://github.com/felipems/cs244_final_project)

**Comment by obormot** [comment]
A "memory leak in dpkt", really??
Skimming over https://github.com/felipems/cs244_final_project/blob/master/detector.py, they're creating dpkt IP or Ethernet object for every packet in the pcap and *appending those to a list*. The list grows, memory grows; it's by design. Every million entries they call gc.collect() to supposedly deal with the "memory leak".

```
        for ts, buf in pcap:
            if raw_ip:
                try:
                    ip = dpkt.ip.IP(buf)
                except :
                    continue           
            else:
                eth = dpkt.ethernet.Ethernet(buf)
                ip = eth.data
            all_packets.append(ip)             <<<---  "memory leak" here YEAH
            sample_packet(ip,bad_ips,good_ips);
            if len(all_packets)%1000000 ==0:             
                print len(all_packets)/1000000," million"
                gc.collect()
```

**Comment by brifordwylie** [comment]
So constructively perhaps we can touch base with the authors and recommend a 'generator' based approach...
