### ISSUE TITLE
Problem in Fetching port

### ISSUE THREAD

**Issue by manishkk** [kbandla/dpkt#316]
I am trying to fetch sender/ receiver port details from pcap file using python Django.

I am using following code but getting error

**_'str' object has no attribute 'dport'_**

Please correct me If I am doing wrong.
Thanking you in advace

```
f =  open("/home/manish/PycharmProjects/pcap/webapp/Test_1.pcap")

pcap = dpkt.pcap.Reader(f)

for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    ip = eth.data
    tcp = ip.data

    if tcp.dport == 80 and len(tcp.data) > 0:
        http = dpkt.http.Request(tcp.data)

def index(request):
                answer = [

                         str(http.uri)


                        ]

                return HttpResponse("<br>" . join(answer))

**Comment by obormot** [comment]
@manishkk you're likely hitting a non-TCP packet (e.g. an ARP or ICMP). You can try the following (untested):
```
from dpkt.tcp import TCP
...
for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    ip = eth.data
    tcp = ip.data

    if not isinstance(tcp, TCP):
        continue

    if tcp.dport == 80 and len(tcp.data) > 0:
        http = dpkt.http.Request(tcp.data)
```

**Comment by manishkk** [comment]
nice, It's not giving error but not returning anything in out put also.
yes, you are right, Just now i checked in cloud shark, the protocol type is ARP, HSRPv2, STP etc.

for source & destination port what should I use instead of 

```
http.uri
