### ISSUE TITLE
IEEE80211 Prints error directly to CLI

### ISSUE THREAD

**Issue by looopTools** [kbandla/dpkt#322]
In the IEEE80211 class's `unpack` method on line [418](https://github.com/kbandla/dpkt/blob/2208e638f8f3939ba877a595ce75925710500a44/dpkt/ieee80211.py#L418). There is a print statement exposing the error directly to CLI. 

This is a problem if one is to use DPKT in combination with for instance [curses](https://docs.python.org/2/howto/curses.html), as it disrupts the UI of the developed application.  Therefore we suggest removing this print statement and instead return an error code of some sort. 

EDIT: 
From what I can tell you could either just let the developer handle the exception self, or simply delete the print statement

**Comment by obormot** [comment]
I agree, looks like IEEE80211 is the only decoder where such print is present. A correct thing to do would be to replace the ```print(text, args)``` with ```raise dpkt.UnpackError(text, args)``` (and remove the following return)

**Comment by obormot** [comment]
@looopTools Please see https://github.com/kbandla/dpkt/pull/326 looks good?

**Comment by looopTools** [comment]
@obormot looks good to me :)

**Comment by obormot** [comment]
Ok, merged and closed
