### ISSUE TITLE
ICMP payload inside IP packets isn't parsed under Python2

### ISSUE THREAD

**Issue by Tojaj** [kbandla/dpkt#324]
Current code in dpkt git (1.9.0) cannot parse ICMP packets (and some other protocols) when run under Python2, but works fine under Python3.

My git HEAD is 65b3d9716b80d17e5bffb66f57230ddeee384f75

## Reproducer

    import dpkt
    with open("ip_frag_source.pcap", 'rb') as f:
        pcap = dpkt.pcap.Reader(f)
        for ts, buf in pcap:
            eth = dpkt.ethernet.Ethernet(buf)
            ip = eth.data
            print(type(ip.data))

Note: The PCAP file ``ip_frag_source.pcap`` can be downloaded from http://chrissanders.org/packet-captures/

### Python 2

    $ python2.7 reproducer.py
    <type 'str'>
    ....

### Python 3

    $ python3.5 reproducer.py
    <class 'dpkt.icmp.ICMP'>
    ....

## Debugging

I added raise statement into ``__load_protos`` function in ``ip.py`` to see the exception:

    try:
        mod = __import__(name, g, level=1)
        IP.set_proto(v, getattr(mod, name.upper()))
    except (ImportError, AttributeError) as err:
        if name == "icmp":  # XXX Debug
            raise           # XXX Debug
        continue

and result is:

    $ python2.7 ./reproducer.py 
    Traceback (most recent call last):
      File "./reproducer.py", line 3, in <module>
        import dpkt
      File "/home/tojaj/git/dpkt/dpkt/__init__.py", line 33, in <module>
        from . import icmp
      File "/home/tojaj/git/dpkt/dpkt/icmp.py", line 8, in <module>
        from . import ip
      File "/home/tojaj/git/dpkt/dpkt/ip.py", line 362, in <module>
        __load_protos()
      File "/home/tojaj/git/dpkt/dpkt/ip.py", line 354, in __load_protos
        IP.set_proto(v, getattr(mod, name.upper()))
    AttributeError: 'module' object has no attribute 'ICMP'

### Code

    import dpkt
    from pprint import pprint
    pprint(dpkt.ip.IP._protosw)

### Python2

    $ python2.7 ./reproducer.py 
    {0: <class 'dpkt.ip.IP'>,
     2: <class 'dpkt.igmp.IGMP'>,
     4: <class 'dpkt.ip.IP'>,
     6: <class 'dpkt.tcp.TCP'>,
     17: <class 'dpkt.udp.UDP'>,
     41: <class 'dpkt.ip6.IP6'>,
     50: <class 'dpkt.esp.ESP'>,
     51: <class 'dpkt.ah.AH'>,
     89: <class 'dpkt.ospf.OSPF'>,
     103: <class 'dpkt.pim.PIM'>,
     112: <class 'dpkt.vrrp.VRRP'>,
     118: <class 'dpkt.stp.STP'>,
     132: <class 'dpkt.sctp.SCTP'>}

### Python3

    $ python3.5 ./reproducer.py 
    {0: <class 'dpkt.ip.IP'>,
     1: <class 'dpkt.icmp.ICMP'>,
     2: <class 'dpkt.igmp.IGMP'>,
     4: <class 'dpkt.ip.IP'>,
     6: <class 'dpkt.tcp.TCP'>,
     17: <class 'dpkt.udp.UDP'>,
     41: <class 'dpkt.ip6.IP6'>,
     47: <class 'dpkt.gre.GRE'>,
     50: <class 'dpkt.esp.ESP'>,
     51: <class 'dpkt.ah.AH'>,
     58: <class 'dpkt.icmp6.ICMP6'>,
     89: <class 'dpkt.ospf.OSPF'>,
     103: <class 'dpkt.pim.PIM'>,
     112: <class 'dpkt.vrrp.VRRP'>,
     118: <class 'dpkt.stp.STP'>,
     132: <class 'dpkt.sctp.SCTP'>}

As you can see ``ICMP``, ``GRE`` and ``ICMP6`` protocols are missing from ``dpkt.ip.IP._protosw`` dict under Python2 in comparison to Python3.

**Comment by Tojaj** [comment]
From the traceback, it's obvious that problem is that ``__init__.py`` imports ``icmp.py`` which imports ``ip.py`` which imports ``icmp.py`` during construction of ``dpkt.ip.IP._protosw`` dict (== circular import).

When ``icmp.py`` imports ``ip.py`` that module is not imported yet (it's listed later then ``icmp.py`` in the ``__init__.py``), thus first (real) import of ``ip.py`` is triggered from inside of ``icmp.py`` which means that ``icmp.py`` which is needed inside ``ip.py`` isn't fully loaded yet and thus ``ICMP`` class is not available for the ``ip.py`` module => The class cannot be added into ``dpkt.ip.IP._protosw`` => ICMP protocol is not supported in IP packets.

This issue could be simply avoided by removal of import of ``ip`` module from the beginning of ``icmp.py`` and usage of the ``ip`` module there like ``dpkt.ip.IP()`` instead of ``ip.IP()``:

    diff --git a/dpkt/icmp.py b/dpkt/icmp.py
    index 214a950..54411e1 100644
    --- a/dpkt/icmp.py
    +++ b/dpkt/icmp.py
    @@ -5,7 +5,6 @@ from __future__ import print_function
     from __future__ import absolute_import
     
     from . import dpkt
    -from . import ip
     
     # Types (icmp_type) and codes (icmp_code) -
     # http://www.iana.org/assignments/icmp-parameters
    @@ -98,7 +97,7 @@ class ICMP(dpkt.Packet):
     
             def unpack(self, buf):
                 dpkt.Packet.unpack(self, buf)
    -            self.data = self.ip = ip.IP(self.data)
    +            self.data = self.ip = dpkt.ip.IP(self.data)
     
         class Unreach(Quote):
             __hdr__ = (('pad', 'H', 0), ('mtu', 'H', 0))

**Comment by Tojaj** [comment]
Looking at the GRE issue, during debugging I found out that code:

    # XXX - auto-load GRE dispatch table from Ethernet dispatch table
    from . import ethernet
    GRE._protosw.update(ethernet.Ethernet._typesw)

from ``gre.py`` is actually called multiple time and the first call returns: ``cannot import name ethernet``.

I looked to it and found out that although in ``__init__.py`` the ``ethernet`` module is imported before ``gre``:

    from . import ethernet
    from . import gre

That in fact the import of ``ethernet`` module leads into import of ``gre`` which then tries to import ``ethernet`` which isn't fully loaded yet (another circular dependency).

The call stack is following:

1) ``import dpkt`` is called from an external code (reproducer in my case)
2) ``__init__.py`` calls ``from . import ethernet`` on line ``27``
3) ``ethernet.py`` calls ``__load_types()`` on line ``254``, the function is in the same module and causes that ``ip6.py`` module is imported.
4) ``ip6.py`` imports ``ip`` module on line ``146``
5) ``ip.py`` calls ``__load_protos()`` on line ``362``, the function is in the same file (``ip.py``)
6) the ``__load_protos()`` imports modules corresponding to constants with ``IP_PROTO_`` in ``ip.py`` file. The ``gre`` module is there too.

Thanks to this, ``gre`` module is actually being imported from ``ip`` module during initialization of ``ethernet`` module. But ``gre`` needs ``ethernet`` module (which is not ready yet), thus the first initialization (the one called from ``ip``) fails. In the end, ``gre`` is fully initialized once it's directly imported from ``__init__.py``, but in that time, ``ip`` is already loaded and misses support for ``gre`` (because when ``ip`` was loading ``gre`` it failed).

@obormot, @brifordwylie 
Thinking about that, it maybe worth it to actually call ``__load_protos()`` and similar functions during first instantiation of ``IP``, ``IP6``, etc. classes (i.e. in time when all modules are most likely already initialized) and not during module initialization.

**Comment by obormot** [comment]
oops.. mistakenly referred this in another issue (326 vs 324), my bad @Tojaj

**Comment by Tojaj** [comment]
This issue was resolved by PR #330
