### ISSUE TITLE
New release for python3 support

### ISSUE THREAD

**Issue by RemiDesgrange** [kbandla/dpkt#334]
Hi, 

Super super great news that dpkt support python3, I tried it myself but it was too much of a hassle and I didn't understand what I was doing.

Since the code in the repo support python3, but the PyPi release doesn't, can you make a release that can be downloadable from pip ? thank.

**Comment by JockDaRock** [comment]
Agreed!  would love to see this moved to pip :-)

**Comment by brifordwylie** [comment]
We're just waiting on reviews for https://github.com/kbandla/dpkt/pull/336 and then we'll set up a new pypi release with support for Python 3.

**Comment by JockDaRock** [comment]
Thank you for the response! And Understood :). Yeah, I have ran into that problem myself with Python3 on projects. Very annoying! Lol

**Comment by brifordwylie** [comment]
Python3 code pushed to pypi: https://github.com/kbandla/dpkt/releases/tag/v1.9.0

**Comment by JockDaRock** [comment]
Awesome, can't wait to include it in build I am about to push out today ;-)
