### ISSUE TITLE
Handle non-ascii HTTP Headers

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#340]
From @scott-hand
RFC 7230 advice: "In practice, most HTTP header field values use only a subset of the US-ASCII charset [USASCII]. Newly defined header fields SHOULD limit their field values to US-ASCII octets. A recipient SHOULD treat other octets in field content (obs-text) as opaque data."

Right now (after https://github.com/kbandla/dpkt/pull/336 is merged) non-ascii characters in the header will be silently dropped.

**Comment by brifordwylie** [comment]
@scott-hand so this issue is a 'code quality' issue, meaning that the functionality you already checked in for Python3 support should work on the vast majority of use cases. So IMO this is not a high priority item and the Python3 PyPi release will not block on it. But having said all that.. is this something you could put on your low-priority queue?

**Comment by scott-hand** [comment]
@brifordwylie Sure. The only issue is that, as I mentioned in the PR, it's literally impossible to handle headers and protocol fields in decoded strings in Python 3 while maintaining 100% of the data. So it's really a question of whether people want to stick to bytes end-to-end.

**Comment by brifordwylie** [comment]
@scott-hand right.. okay.. well I really do think the functionality that you've already committed is probably the best approach... so.. perhaps we'll just close this. Also I've pushed the new dpkt to pypi.. so give it a test when you get a chance :)

**Comment by scott-hand** [comment]
@brifordwylie Looks good on my end, thanks again for pushing it through
