### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#341]
As part of the Python 3 release we're going to remove the deprecated methods in the current source code. A note will be made in the readme me about this and folks will be pointed to the 1.8.8 version if they want to use those methods.

**Comment by kylekeppler** [comment]
Do you have a list of what will be depreciated? Would help people port their code before the release.

**Comment by brifordwylie** [comment]
@kylekeppler All of the methods marked for deprecation have an @deprecated decorator around them:

```
    # Deprecated methods, will be removed in the future
    # =================================================
    @deprecated('v')
    def _get_v(self):
        return self.v
```

@saylenty did a nice job on the decorators. Basically whenever you use one of the deprecated methods you get the follow message:

```
packet._get_v()
DeprecationWarning: Call to deprecated method _get_v; use v instead
```

These methods have been marked as deprecated since 2015-06-01. So that's what? A year and 9 months of deprecation warnings/messages. At this point if people haven't migrated their code then they probably have a legacy situation and they'll probably opt to stay with an older version of dpkt anyway. We will add a big message to the README that refers folks to the 1.8.8 version for legacy code stability.

**Comment by kylekeppler** [comment]
Perfect. Guess I haven't used any depreciated methods as I haven't seen the Warning yet.

**Comment by brifordwylie** [comment]
Closing with the merge of #354
