### ISSUE TITLE
Problem importing dpkt in python 2.7 with Windows10

### ISSUE THREAD

**Issue by Rigstor** [kbandla/dpkt#359]
Good morning,

I am having trouble with Python 2.7. I try to import dpkt and an error occurs

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import dpkt
ImportError: No module named dpkt

I am using Windows 10 and have successfully install dpkt

**Comment by brifordwylie** [comment]
@Rigstor when you installed did you do
```
pip install dpkt
```
 you might also try
```
python -m pip install dpkt
```
to see if that makes any difference.

**Comment by kbandla** [comment]
Will test this today, I have a win10 box.

**Comment by kbandla** [comment]
@Rigstor any updates? 
I checked out the master branch on a Window10 x64 computer, and dpkt seems to load/work fine.

**Comment by traumschule** [comment]
ran into this on debian buster just now, the suggested alternative works. should the README be updated?

**Comment by aygupt1822** [comment]
> ran into this on debian buster just now, the suggested alternative works. Clarification: `pip install dpkt` is not enough, only after `python -m pip install dpkt` i was able to use the library. should the README be updated?

I agree with you. I just had same problem as @Rigstor had, I was able to import **`dpkt`** by `python -m pip install dpkt`. You were correct, `pip install dpkt` was not enough.

**Comment by brifordwylie** [comment]
this has nothing to do with dpkt... when `pip install <some package>` doesn't work and `python -m pip install <some package>` does work, it simply means that you have multiple python environments and your `pip` command is for another python interpreter. Just do a `which pip` and a `which python` and there's probably a mis-match. I'm closing this as not a dpkt issue.
