### ISSUE TITLE
Recursion error when creating a string from an ICMP packet.

### ISSUE THREAD

**Issue by averagesecurityguy** [kbandla/dpkt#360]
I'm using the following code to build an ICMP packet.
```
def build_icmp_echo(id=0, seq=0, data=''):
    echo = dpkt.icmp.ICMP.Echo()
    echo.id = id
    echo.seq = seq
    echo.data = data

    icmp = dpkt.icmp.ICMP()
    icmp.type = dpkt.icmp.ICMP_ECHO
    icmp.data = str(data)

    return icmp
```
When I call str() on the ICMP object I get the following stack trace:
```
 File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 141, in __str__
    return str(self.__bytes__())
  File "/usr/local/lib/python2.7/dist-packages/dpkt/icmp.py", line 130, in __bytes__
    self.sum = dpkt.in_cksum(dpkt.Packet.__str__(self))
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 141, in __str__
    return str(self.__bytes__())
  File "/usr/local/lib/python2.7/dist-packages/dpkt/icmp.py", line 130, in __bytes__
    self.sum = dpkt.in_cksum(dpkt.Packet.__str__(self))
```

The stack trace continues like this until a max recursion depth error is reached. The `ICMP.__bytes__()` method is calling the `dpkt.Packet.__str__()` method, which calls the `ICMP.__bytes__()` method. This only affects 1.9.0, so I assume it is an artifact of adding the Python 3 support. I am running my code in Python 2.7.

**Comment by obormot** [comment]
Fix is underway. Thx for reporting @averagesecurityguy

**Comment by stillinsecure** [comment]
I had the same issue tonight and this fixed me up, thanks.

**Comment by brifordwylie** [comment]
We probably need to push a new PyPI release.

**Comment by averagesecurityguy** [comment]
Thank you for taking care of this so quickly.
