### ISSUE TITLE
TCP/DNS not supported

### ISSUE THREAD

**Issue by SinBirb** [kbandla/dpkt#363]
Thanks for the awesome library. It would be nice if you can add support for DNS over TCP. AFAIK the only difference to UDP is that there are two bytes before the DNS data that specify the length.

**Comment by obormot** [comment]
[sample capture](https://github.com/aol/moloch/blob/master/tests/pcap/dns-tcp.pcap)
RFC 1035:

> 4.2.2. TCP usage
> 
> Messages sent over TCP connections use server port 53 (decimal). The message is prefixed with a two byte length field which gives the message length, excluding the two byte length field. This length field allows the low-level processing to assemble a complete message before beginning to parse it.

**Comment by obormot** [comment]
https://github.com/kbandla/dpkt/issues/386

**Comment by obormot** [comment]
old issue; resolved (see #386); closing
