### ISSUE TITLE
http header parse problem in http.py

### ISSUE THREAD

**Issue by daohu527** [kbandla/dpkt#364]
the code like this
        l = line.split(':', 1)
        if len(l[0].split()) != 1:
            raise dpkt.UnpackError('invalid header: %r' % line)

I have a testcase like this:
    s = b'POST /main /redirect/ab/1,295,,00.html HTTP/1.0\r\n' \
        b'Referer\r\n' \
        b'Connection: Keep-Alive\r\n' 
then r.headers will add Referer, but Referer don't have a ':'

**Comment by kbandla** [comment]
Closing this issue. Looks like @daohu527 has a new one opened with updated info. See #365
