### ISSUE TITLE
http.py a little improve

### ISSUE THREAD

**Issue by daohu527** [kbandla/dpkt#365]
line 34 in http.py
i think
```
        l = line.split(':', 1)
        if len(l) < 2:
            raise UnpackError('invalid header: %r' % line)
        k = l[0]
        v = l[1].strip()
```
I'm not so sure, if space in header in right like this
```
    s = b'POST /main /redirect/ab/1,295,,00.html HTTP/1.0\r\n' \
        b'Referer:\r\n' \
        b'Connection: Keep-Alive\r\n' \
        b'User-Agent: Mozilla/4.75 [en] (X11; U; OpenBSD 2.8 i386; Nav)\r\n' \
        b'Host ID: ltd.snap.com\r\n' \'
```
which Host ID is an example, I find some http app use like this.but not so sure it's right or wrong

**Comment by kbandla** [comment]
hey @daohu527 do you have a pcap for us to test this?

**Comment by daohu527** [comment]
@kbandla I not so inconvenient to send the data,I have see the pcap again,it's a vedio app in ipad named 'QIYI', the pcap info is 'qiyi_ipad_201200418__v3.0_01', so the date is 201200418., it's to old, I copy the header below:

GET /api/uploadRc?key=f0f6c3ee5709615310c0f053dc9c65f2&version=3.1&auth=0&did=e6e947893049807a&type=json&screen_status=2&videoId=431ae2df5c4d482fb2acfe22d263f122&videoName=%22%E7%B2%BE%E8%A3%85%E8%BF%BD%E5%A5%B3%E4%BB%94%E4%B9%8B3%E7%8B%BC%E4%B9%8B%E4%B8%80%E6%97%8F%22&videoDuration=5211&terminalId=22&videoPlayTime=121.978119&tvId=187525&allSet=1&albumId=168463&nextTvid=187525&nextVideoUrl=1 HTTP/1.1

Host: iface.qiyi.com

User-Agent: QIYI/3.1 (iPad;en-US;Build:(null))

Content-Type: application/x-www-form-urlencoded

QIYI/3.1 (iPad;en-US;Build:(null)): User-Agent                     //which is wrong

Accept-Encoding: gzip

Connection: keep-alive

so, maybe the pcap and app it's old version, but the problem is how to find the ':', and should headers have space?
I also see the python lib like rfc822.py, headers judge like this:

    def isheader(self, line):
        """Determine whether a given line is a legal header.

        This method should return the header name, suitably canonicalized.
        You may override this method in order to use Message parsing on tagged
        data in RFC 2822-like formats with special header formats.
        """
        i = line.find(':')
        if i > -1:
            return line[:i].lower()
        return None

I'm dealing with some special headers for many apps,so I have the questiones, thks

**Comment by kbandla** [comment]
iirc, Header values are allowed to have a beginning space in the RFC. 
Also, dpkt's goal is to have a best-effort way to parse http headers, even if they are non-conforming with the RFC.
