### ISSUE TITLE
Unable to parse DNS packet over TCP

### ISSUE THREAD

**Issue by codingbond** [kbandla/dpkt#386]
DNS protocol works on udp port 53 as well as tcp port 53.
I am able to parse dns packet of udp port 53 using dpkt but unable to parse packets of tcp port 53. Wireshark extract every fields from udp port 53 as well as tcp port 53 packet perfectly.
![tcp_dns](https://user-images.githubusercontent.com/28299081/30521038-e467e874-9bb8-11e7-937b-3e326314d0fd.png)

Sample Data:-
```
IP(len=94, id=63784, off=16384, p=6, sum=51064, src='\n\xbc\x99\xa7', dst='\n\xc8\xca\xcd', opts='', data=TCP(sport=16883, dport=53, seq=1770261319, ack=2968858173, off=8, flags=24, sum=27405, opts='\x01\x01\x08\n\x00\xf8\xf2ic\x18\x07\x1c', data='\x00(2\xac\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06rtb-tm\x0beveresttech\x03net\x00\x00\x01\x00\x01'))
>>> tcp = ip.tcp
>>> tcp
TCP(sport=16883, dport=53, seq=1770261319, ack=2968858173, off=8, flags=24, sum=27405, opts='\x01\x01\x08\n\x00\xf8\xf2ic\x18\x07\x1c', data='\x00(2\xac\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06rtb-tm\x0beveresttech\x03net\x00\x00\x01\x00\x01')
```
Is dpkt able to parse these type of packets? If no then any idea how to parse these packets?
I try to parse using python struct, but this method was pretty slow, i am hoping fast way like dpkt function.

**Comment by smutt** [comment]
Wireshark does automatic stream reconstruction for TCP. Make sure the DNS data you're trying to parse is actually in one TCP packet and not spread across multiple packets.

**Comment by codingbond** [comment]
I double check wireshark extract data from single packet of dns over tcp protocol.
Follow tcp stream screenshot:
![screenshot from 2017-09-24 15-41-18](https://user-images.githubusercontent.com/28299081/30782654-ec3767e2-a13e-11e7-9b3c-283af2cf30f4.png)

**Comment by crocogorical** [comment]
DNS over TCP includes a 2 byte length field at the start of the TCP PDU which is not present when using UDP. If you remove it, dpkt will parse your record. RFC is [here](https://www.rfc-editor.org/rfc/rfc7766.txt) (see Section 8).

```
IP(len=94, id=63784, off=16384, p=6, sum=51064, src='\n\xbc\x99\xa7', dst='\n\xc8\xca\xcd', opts='', data=TCP(sport=16883, dport=53, seq=1770261319, ack=2968858173, off=8, flags=24, sum=27405, opts='\x01\x01\x08\n\x00\xf8\xf2ic\x18\x07\x1c', data='\x00(2\xac\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06rtb-tm\x0beveresttech\x03net\x00\x00\x01\x00\x01'))
>>> tcp = ip.tcp
>>> tcp
TCP(sport=16883, dport=53, seq=1770261319, ack=2968858173, off=8, flags=24, sum=27405, opts='\x01\x01\x08\n\x00\xf8\xf2ic\x18\x07\x1c', data='\x00(2\xac\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06rtb-tm\x0beveresttech\x03net\x00\x00\x01\x00\x01')
>>> dpkt.dns.DNS(tcp.data[2:])
DNS(id=12972, qd=[Q(name='rtb-tm.everesttech.net')])
```

**Comment by obormot** [comment]
old issue; resolved; closing
