### ISSUE TITLE
python2.6 support

### ISSUE THREAD

**Issue by crocogorical** [kbandla/dpkt#394]
Is there a planned EOL date for python2.6 support?

Last release was 2008, and it has a sufficiently different standard library to make code that works on 2.7, fail on 2.6.

To make things easier to develop/maintain, can support for 2.6 be removed in release 2.0.0?

**Comment by brifordwylie** [comment]
@crocogorical I agree that deprecating 2.6 (and including 3.6) should be done. The only caveat here is that dpkt gets run in a lot of places, some with older machines/software. We'll have to get consensus here from @kbandla and @obormot before moving forward.

**Comment by crocogorical** [comment]
`pytest` as of v3.3 2017/11/27 (https://docs.pytest.org/en/latest/changelog.html) no longer supports python2.6.

**Comment by crocogorical** [comment]
`setuptools` as of v38.2.2 2017/11/20 (https://github.com/pypa/setuptools/commit/89ef5bb7e4812193d6f593d531bad36191517981) has dropped support for python2.6. The latest version in pypi that supports 2.6 is 36.8.0

**Comment by crocogorical** [comment]
`wheel` as of v0.30.0 2017/09/10 (https://pypi.python.org/pypi/wheel/0.30.0) has dropped support for python2.6. The latest version in pypi that supports 2.6 is 0.29.0

**Comment by brifordwylie** [comment]
@kbandla @obormot Hey, so we need to deprecate Python 2.6 (heck Python 2 is dead at the end of this year). So anyway I want to get an 'okay' from both of you on this deprecation and then I'll do it.

**Comment by obormot** [comment]
sounds good to me!

**Comment by obormot** [comment]
dpkt no longer lists 2.6 as supported; this can be closed
