### ISSUE TITLE
count IPv6 Extension headers 

### ISSUE THREAD

**Issue by mimta** [kbandla/dpkt#400]
Hi Guys
I've did everything I know to get number of extension header in a packet. 
For example I have a packet with 100 extension headers! but I can only see on them
`<bound method IP6.unpack of IP6(v=6, fc=0, flow=8, plen=1182, nxt=60, hlim=255, src='\xfd\x17b\\\xf07\x00\x02=\xd0\x9f0\x8d\xd9\x08f', dst='\xfd\x17b\\\xf07\x00\x02d\x89\xcb\x90T\xb2\x8ai', p=58, extension_hdrs={60: IP6DstOptsHeader(nxt=58, length=8, options=[{'opt_length': 0, 'data': '', 'type': 31}], data='\x1f\x00\x00\x00\x00\x00\x80\x00\x02\xf2\x00\x00\x00\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08')}, data=ICMP6(type=128, sum=754, data=Echo(seq=8, data='\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08')))>
`

Any help?!

**Comment by crocogorical** [comment]
Did you try `len(ip6.extension_hdrs)` where `ip6` is your packet?

If that doesn't work, can you please post what you tried?

**Comment by mimta** [comment]
it didnt work,
I am trying to get how many extension headers are in this pcap file
https://www.dropbox.com/s/gt6bphlh6b74ig3/8-1.pcap?dl=0

> def get_ethernet_frame (buf):
>     try:
>         return dpkt.ethernet.Ethernet(buf)
>     except:
>         return False
> 
> def get_ip_packet (ethernet_frame):
>     return ethernet_frame.data
> 
> def packet_has_extention_hdrs(ip_packet):
>     try:
>         if ip_packet.extension_hdrs:
>            return True
>     except:
>         return False

I'll appropriated your help.

**Comment by crocogorical** [comment]
Ok, I see the problem here. The IP6 options parsing can only handle one instance of each option type. Linking this to outstanding bug #159
