### ISSUE TITLE
How to get any field from Wi-Fi beacon

### ISSUE THREAD

**Issue by alchimia** [kbandla/dpkt#401]
Hi everyone,
i found dpkt and it is very fast. But i don't understand how it is possible to get a specific field. I try to explain better: if i need [duration](https://s8.postimg.org/6u4q4iy5x/Schermata_2017-11-21_alle_15.06.19.png), how can i get it?

thank you!

**Comment by crocogorical** [comment]
Can you please post an example packet and what you have already tried?

The IEEE80211 class has a `duration` header attribute. Does this not do what you want?

**Comment by alchimia** [comment]
Hi @crocogorical, thanks for your reply. I got duration attribute in this way:
```
printDebugInformation("FULL LENGHT: " + str(len(buf)))
        rd_len = radioHeader.length >> 8
        length = len(buf) - rd_len# - radioHeader.length
        printDebugInformation("LENGHT: " + str(length))
        duration = float(8*(length ))/float(radioHeader.rate.val/2)
        if (radioHeader.flags_present and radioHeader.flags.val & 0x02):
      #short preamble
            duration += 96
        else:
            duration += 192
        printDebugInformation("DURATA: " + str(duration))
```
The problem is that now i need other fields, for example [this one](https://s33.postimg.org/930wlmqyn/Schermata_2017-11-27_alle_00.07.57.png). How can i parse it? [Here you can find my test pcap file](https://mega.nz/#!Uw1ACLST!m8s67EIXyAf2G98dhwwW_LO-3F93Gnv8T_paYYTJMZU).

Thank you.

**Comment by crocogorical** [comment]
I'm afraid I don't really follow your code. Could you perhaps in future provide a code example that executes?

It appears that the information element that you are trying to access hasn't been implemented.
```python3
import struct
import binascii
import dpkt
buf = b'000012002e48000000166c09a000b501000080000000fffffffffffff47f359948b0f47f359948b0f09dd9e07dd73000000066002114000354555401079618243048606c0301010504000100000706464920010d140b0503002a8d5b2a01002d1a2c181bfeff0000000000000000000000000000000000000000003d16010005000000000000000000000000000000000000007f06001000000040851e04008f000f00ff03590074742e7761702d336400000000000000030000369606004096000b00dd180050f2020101800003a4000027a4000042435e0062322f00dd06004096010104dd050040960305dd050040960b09dd050040961400dd1d0040960c0382d8c475a4dc5f0100000000000000000000000000000000'

pkt = dpkt.radiotap.Radiotap(binascii.unhexlify(buf))
ieee80211 = pkt.data
qbss = ieee80211.ie_11 

station_count, channel_utilization, available_admission_capabilities = struct.unpack('<HBH', qbss.info)
print('station count', station_count)
print('channel_utilization', channel_utilization)
print('available_admission_capabilities', available_admission_capabilities)
```

This should extract the information from packet 813 in your linked data, and show you how to extract the information that you want.

In general, all information elements are extracted into an `.ie_XX` where `XX` is the decimal value of the Information Element. You can find the code for this in `dpkt/ieee80211.py` under `unpack_ies`. Ones that have been fully parsed will be accessible by named attribute of an `IEEE80211` object. Those are:

```python
ie_decoder = {
            IE_SSID: ('ssid', self.IE),
            IE_RATES: ('rate', self.IE),
            IE_FH: ('fh', self.FH),
            IE_DS: ('ds', self.DS),
            IE_CF: ('cf', self.CF),
            IE_TIM: ('tim', self.TIM),
            IE_IBSS: ('ibss', self.IBSS),
            IE_HT_CAPA: ('ht_capa', self.IE),
            IE_ESR: ('esr', self.IE),
            IE_HT_INFO: ('ht_info', self.IE)
}
```

HTH

**Comment by alchimia** [comment]
Hi @crocogorical, i can't found your twitter to tell you very thanks in pvt.

Anyway, about duration, i wanted to get [this field](https://s8.postimg.org/6u4q4iy5x/Schermata_2017-11-21_alle_15.06.19.png): is there a better way to parse it?

You code works about package 813 but i can't add it [in my code](https://mega.nz/#!psMgVRQY!50_axN8Zr7dnnVh6LX6t5BnQU1RGYYvMXF6BNA_2sTc).

**Comment by alchimia** [comment]
Hi @crocogorical, i can't found your twitter to tell you very thanks in pvt.

Anyway, about duration, i wanted to get [this field](https://s8.postimg.org/6u4q4iy5x/Schermata_2017-11-21_alle_15.06.19.png): which is the better way to parse it?

And if need others fields, [for example this](https://s8.postimg.org/p0n2m5251/Schermata_2017-11-27_alle_16.12.12.png), how can i do?

**Comment by crocogorical** [comment]
Hi @alchimia, no thanks needed, just pay it forward.

On duration, the square brackets show that it is a wireshark calculated field. I'm not sure how it generated this information, but I do not think that your code above is correct, as running it on packet 813 (above) returns a duration of 587 us, rather than 384+192==576 us which is what wireshark shows.

As to the Fixed Parameters, they are extracted initially into a `beacon` field of the `IEEE80211` class. These, however are just the bytes that have been pulled from the fixed length fields. You can access the `timestamp`, `interval` and `capability` fields in this way.

The capability information bit fields are extracted to a `capability` field, accessible as fields on that object.

```
>>> print(hex(ieee80211.beacon.timestamp))
'0xd9e07dd73000000'
>>> print(hex(ieee80211.beacon.interval))
'0x6600'
>>> print(ieee80211.beacon.capability)
'0x2114'
>>> print(ieee80211.capability.ess)
1
>>> print(vars(ieee80211.capability))
{'imm_blk_ack': 0, 'cf_poll_req': 0, 'ibss': 0, 'apsd': 0, 'short_slot': 1, 'delayed_blk_ack': 0, 'spec_mgmt': 0, 'dsss': 0, 'cf_poll': 0, 'ess': 1, 'short_preamble': 1, 'pbcc': 0, 'hopping': 0, 'privacy': 0, 'qos': 0}
```

In general, I find the easiest way to find out how things work is just to print the `repr` of the packet and then look for something that looks like what I want.

HTH

**Comment by obormot** [comment]
answered - closing
