### ISSUE TITLE
Modifying PCAP input files using DPKT

### ISSUE THREAD

**Issue by jonasanmaru** [kbandla/dpkt#402]
Is is possible to use dpkt.pcap.Writer to write into a new file by modifying the 'original traces being input?'

> #Input Original Traces
fileinput  = open('original.pcap','rb')
reader     = dpkt.pcap.Reader(fileinput)

> #Output Modified Traces 
fileoutput = open('modified.pcap','wb')
writer     = dpkt.pcap.Writer(fileoutput)

> for ts, pkt in reader:
    eth_packet = dpkt.ethernet.Ethernet(pkt)
    ip = eth_packet.data
    #ip.src = "0.0.0.0
    #is it possible to replace all source ip address to 0.0.0.0 and
    #write it back into the original pcap file or a new pcap file?
    writer.writepkt(pkt)

**Comment by obormot** [comment]
Non-issue; closing

**Comment by marty90** [comment]
Sorry but if I modify and the rewrite, I cannot find the modification in the PCAP. Are you sure this works??

**Comment by obormot** [comment]
@marty90 please provide an example code that doesn't work for you

**Comment by marty90** [comment]
I found the way:
Using the example above.
If I write: `writer.writepkt(pkt)` it writes the original (unmodified) packet.
Do write the modified packet, I need to write: `writer.writepkt(pkt)`

**Comment by vermish6** [comment]
can someone tell me like I am trying to anonymize IP addresses of very big pcap files so I am using dpkt as it is faster for parsing files, so I am encountering a problem that is in writing to a pcap file using dpkt writer 
This is the code 
    with open(output_pcap_file, 'wb+') as f:
        pcap_writer = dpkt.pcap.Writer(f)
        for ts, packet in anonymized_packets:
            pcap_writer.writepkt(packet,ts)
In this I am getting error that argument for 's' must be a bytes object , here ts is the timestamp of type float and packet of type <class 'dpkt.ethernet.Ethernet> , please tell what is wrong here
