### ISSUE TITLE
http response Unpack Error 

### ISSUE THREAD

**Issue by 747905245** [kbandla/dpkt#406]
I want to get the html content from a http response packet. However, when I print all response.body, I cannot find that content. Then I find all those packets are defined as wrong packets.

When I use wireshark，I can see all http content, but if I use dpkt , there is something wrong although response.status is 200.

Here is content I want to find, but it is defined as a invalid packet when using dpkt.
![image](https://user-images.githubusercontent.com/23058623/34453822-45c4da24-ed98-11e7-9d56-252b24dc224b.png)

Sample code:
if is_internal_ip(dst):
	if tcp.sport== 80:	
		try:
			response = dpkt.http.Response(tcp.data);
			if response.status == '200':
				print response.body
		except(dpkt.dpkt.NeedData,dpkt.dpkt.UnpackError):
			pass

How could I fix it and get html content from it ?
Thanks.

**Comment by obormot** [comment]
please attach a pcap

**Comment by obormot** [comment]
cleanup..  >2 years old and no responses; closing.
