### ISSUE TITLE
finding the protocols in frame

### ISSUE THREAD

**Issue by BugByteBuster** [kbandla/dpkt#420]
Hello,
Is it possible to print the protocols in a frame? For example, while viewing a packet in Wireshark, there is an option which shows all the packets in the frame like this **[protocols in frame: eth:ethertype:ip:data]**.
I am interested to print all the protocols [eth:ethertype:ip:data] in the packet. I have seen the document but hard luck. I can only find a way to get the protocol at different layers ex: application or transport. kindly let me know how to know all the protocols available in a frame at once.

**Comment by brifordwylie** [comment]
@vidyadharreddy18 this example should give you a good example of how to do what you want. The example inspects the ethernet frame, the IP packet, the transport layer, and then the data inside (HTTP in this case).
- https://dpkt.readthedocs.io/en/latest/print_http_requests.html

**Comment by vidyadharreddy18** [comment]
Hello @brifordwylie  this is not exactly what I wanted please refer to this question https://stackoverflow.com/questions/13549294/get-all-the-layers-in-a-packet I want this question to be solved using dpkt. Are there any methods in dpkt that could get all the protocols in the frame?
