### ISSUE TITLE
Need the ori_len attribute from packet header of Pcap file

### ISSUE THREAD

**Issue by leoouyang** [kbandla/dpkt#424]
I am trying to analyze packets from a pcap file with dpkt. Since the pcap file is modified to only contain the headers of the packets(Ethernet header, IP header, etc.), I can't get the size of the packet using len(buf). Instead, I need the orig_len field that records the length of packet on wire from the pcap header. Reading the source file, I think the information I want are read here but not stored? "hdr = self.__ph(buf)" in __iter__ function of dpkt.pcap.Reader.

**Comment by obormot** [comment]
There's no easy way to modify the existing code to support this and remain compatible. 
One could modify `pcap.Reader.__iter__` to also yield the original length as follows:
```
    def __iter__(self):
        while 1:
            ...
            hdr = self.__ph(buf)
            buf = self.__f.read(hdr.caplen)
>>          orig_len = hdr.len
>>          yield (hdr.tv_sec + (hdr.tv_usec / self._divisor), buf, orig_len)
```
