### ISSUE TITLE
Add Travis CI Python 3.7 support

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#429]
The Travis CI platform has some issues running Python 3.7 (this is not their fault but an OpenSSL on Trusty issue).. anyway figure out a way to have Travis run Python 3.7 tests.

Travis CI Python 3.7:
- https://github.com/travis-ci/travis-ci/issues/9815

Also see #428 for additional info

**Comment by obormot** [comment]
Resolved by merging https://github.com/kbandla/dpkt/pull/450
Closing
