### ISSUE TITLE
On pypi the link to the project homepage is still dpkt.googlecode.com

### ISSUE THREAD

**Issue by mpd-dude** [kbandla/dpkt#439]
@brifordwylie: thanks for the 1.9.2 release, while checking it out:

https://pypi.org/project/dpkt/1.9.2/
On pypi the link to the project homepage on the left side ("Project links -> Homepage")

is the outdated one: http://dpkt.googlecode.com/

Could you update this link with the current github link? Thanks.

**Comment by obormot** [comment]
Pypi takes the URL from setup.py. 
dpkt's setup.py imports the url from ```dpkt/__init__.py``` ```__url__```, which correctly points to github. Looks like PyPi's fault but perhaps we could workaround it.

**Comment by obormot** [comment]
Project URL is correct starting with 1.9.3, closing 
https://pypi.org/project/dpkt/1.9.3/
