### ISSUE TITLE
UnicodeDecodeError in python3.5

### ISSUE THREAD

**Issue by gtbaby** [kbandla/dpkt#448]
python version: 3.5.3
when I used 
```
f = open('test.pcap')
pcap = dpkt.pcap.Reader(f)
```
to read the pcap file,
some errors appeared like this:

>  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte

**Comment by kstiehl** [comment]
Run into the same problem can you tell me how you fixed it?

**Comment by gtbaby** [comment]
> Run into the same problem can you tell me how you fixed it?

I did not fix it. It runs normally in python2. So, you know....

**Comment by obormot** [comment]
Let's reopen it then

**Comment by bozbil** [comment]
try this:
f = open('test.pcap','rb')

It will run :)

**Comment by obormot** [comment]
Need to open files explicitly in byte mode under py3 for both pcap.Reader and pcap.Writer to work correctly
