### ISSUE TITLE
Regression in v1.9.2 serializing 802.1q VLAN tagged ARP Requests

### ISSUE THREAD

**Issue by hjholtz** [kbandla/dpkt#460]
```
from binascii import hexlify
from dpkt.ethernet import *
from dpkt.arp import *

e = Ethernet()
v = VLANtag8021Q()
v.pri = 0
v.cfi = 0
v.id = 1
e.vlan_tags = [v]
e.dst=b'\xff' * 6
e.src=b'foobar',
e.type=ETH_TYPE_ARP,
a = ARP()
a.sha = b'foobar'
a.spa = bytes((10,10,10,10))
a.tha = b''
a.tpa = bytes((10,10,10,5))
e.data = a
print(v.type, e.type)
print(hexlify(bytes(e)).decode("ASCII"))
print(v.type, e.type)
```

Output with dpkt 1.9.2:
`2048 (2054,)`
`ffffffffffff666f6f62617281000001`**`0800`**`0001080006040001666f6f6261720a0a0a0a0000000000000a0a0a05`
`2048 (2054,)`
the highlighted part is (incorrect) `ETH_TYPE_IP`

Output with dpkt 1.9.1
`2048 (2054,)`
`ffffffffffff666f6f62617281000001`**`0806`**`0001080006040001666f6f6261720a0a0a0a0000000000000a0a0a05`
`(2054,) (2054,)`
the highlighted part is (correct) `ETH_TYPE_ARP`.

Changing the order of the assignments to `e`'s properties (e.g. `vlan_tags` after `type` and/or `payload`) does not help. The only way I was able to get the correct/desired output was by explicitly setting `v.type = ETH_TYPE_ARP`.

I strongly suspect the change in behavior was caused by https://github.com/kbandla/dpkt/commit/63c318f67a1ed1c48c79fbff90759ea0bf71a75d

**Comment by obormot** [comment]
@hjholtz please take a look at the PR.
I had to change your original `a.spa = bytes((10,10,10,10))` to `a.spa = b'\x0a\x0a\x0a\x0a'` for python2 compatibility

**Comment by hjholtz** [comment]
@obormot thanks a lot!

I can confirm that the changes from the PR fix my use case, and that the unit test captures my observation/requirement.
