### ISSUE TITLE
Reassembly of IP/ IPv4/ TCP

### ISSUE THREAD

**Issue by shyamdb** [kbandla/dpkt#467]
Hello, 
I am using DPKT for my Network Sniffed PCAP analysis. DPKT works amazingly well for the same. But, there is a Problem, which i am facing. I found the way to check if the IP/ IPv4/ TCP Packets are fragmented, but, i cannot reassemble them with any in-built method or function. Is there any way for Reassembly of the fragmented packets in a PCAP File? It will be great, if we have any.

**Comment by brifordwylie** [comment]
Hi @shyamdb we recently added an example for truncated DNS packets that might be helpful, please take a look and let us know (https://github.com/kbandla/dpkt/blob/master/examples/print_dns_truncated.py)
