### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 28: character maps to <undefined>

### ISSUE THREAD

**Issue by h3tz** [kbandla/dpkt#476]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 28: character maps to <undefined>

**Comment by kbandla** [comment]
Can you share any more information on how to reproduce this?

**Comment by obormot** [comment]
cleanup..  no repro detail, no response - closing
