### ISSUE TITLE
how to analysis more pcap together

### ISSUE THREAD

**Issue by lixiang957** [kbandla/dpkt#494]
abc = dpkt.pcap.Reader(open(a, 'rb'))
    bcd = dpkt.pcap.Reader(open(b, 'rb'))
    e = dpkt.pcap.Reader(open(b, 'rb'))

  for ts, data in (abc, bcd, e):

**Comment by obormot** [comment]
pcap.Reader gives an iterator, so this is really a basic Python question, not a dpkt issue.
something like this would work:
```
for aa, bb, cc in zip(abc, bcd, e):
    ts1, data1 = aa
    ts2, data2 = bb
    ts3, data3 = cc 
```
