### ISSUE TITLE
error---for ts,buf in pcap

### ISSUE THREAD

**Issue by lmj731** [kbandla/dpkt#496]
dpkt-1.9.4 python3.7.9 win10
parse error
![image](https://user-images.githubusercontent.com/39516838/101615126-babdf680-3a48-11eb-9ad1-a5afa6eed394.png)
the pcap data:
![image](https://user-images.githubusercontent.com/39516838/101615378-0375af80-3a49-11eb-9249-6803c0594f41.png)

**Comment by kbandla** [comment]
@lmj731 : would it be possible to share the pcap?

**Comment by stryker2k2** [comment]
try this:

`for idx,(ts, buf) in enumerate(pcap):`

**Comment by brifordwylie** [comment]
Also it might be helpful to look at our example that handles truncated packets: https://github.com/kbandla/dpkt/blob/master/examples/print_dns_truncated.py

**Comment by obormot** [comment]
No follow up from the OP - closing.
@lmj731 feel free to reopen if needed.
