### ISSUE TITLE
Switch from TravisCI to Github Actions

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#507]
Since we've got a current integration issue with TravisCI anyway.. perhaps we'll just switch to GitHub Actions for the testing of the dpkt package. 

Related:
- codecov action (https://github.com/codecov/codecov-action)
This action siimply submits results to codecov, would be better if there as a GitHub action for the report.. shrug.. maybe 
- https://github.com/marketplace/actions/code-coverage-report

**Comment by obormot** [comment]
FYI getting this message when checking a build on Travis:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

**Comment by brifordwylie** [comment]
Okay so this is now done with the merge of #514, we'll have to remove TravisCI. Unfortunately I cannot do that. @kbandla will have to do it.. there are 3 places to make sure it gets removed from.

1) Webhooks
2) Integrations
3) Branch protections


When doing 3) make sure to ADD the new GithubActions as required for merging. :)

<img width="972" alt="Screen Shot 2020-12-27 at 12 37 45 PM" src="https://user-images.githubusercontent.com/4806709/103178548-f32f4400-4840-11eb-893b-2206db855f8d.png">
