### ISSUE TITLE
Replace coveralls with Github Action

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#522]
We're removing Travis and the accompanying call to coveralls (with the Travis code coverage report). So we need to replace this with Github Action.

Here's some starting points:
- codecov action (https://github.com/codecov/codecov-action)
 
This action siimply submits results to codecov, would be better if there as a GitHub action for the report.. shrug.. maybe
https://github.com/marketplace/actions/code-coverage-report

**Comment by crocogorical** [comment]
Was coveralls removed for a specific reason? We could send direct to coveralls from a Github Action - https://github.com/marketplace/actions/coveralls-python

**Comment by brifordwylie** [comment]
Hey, cool.. yeah I just hadn't circled back to this...  Please go ahead and merge. :)
