### ISSUE TITLE
Installing dpkt through PIP method missing util.py file

### ISSUE THREAD

**Issue by somebodya1** [kbandla/dpkt#540]
Download one from GitHub of dpkt

**Comment by brifordwylie** [comment]
@somebodya1 

Not sure I understand the issue/request. You can install dpkt via standard pip usage...

```
$ pip install dpkt
```

OR you can check out the latest code..

```
$ git clone git@github.com:kbandla/dpkt.git
$ cd dpkt
$ pip install -e .
``

**Comment by kbandla** [comment]
Looks like the current release does not have `utils.py` (which is used in the examples). We need a new release soon.

**Comment by brifordwylie** [comment]
Oh.. I see.. thanks for the clarification, I'll push out a new release real
quick.

**Comment by brifordwylie** [comment]
This was fixed a while back so closing...
