### ISSUE TITLE
Release Notes for 1.9.5

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#548]
Since most of the recent work is from @crocogorical I'm going to assign release notes for upcoming 1.9.5 to him :)

Just a bulleted list of new/fixed stuff I think is fine.

The only thing I have to add is:
- New example that show how to process truncated DNS packets (examples/print_dns_truncated.py)

**Comment by crocogorical** [comment]
Is the best place for them still in the CHANGES file, or should is the plan only to put them in the GitHub releases blurb?

**Comment by brifordwylie** [comment]
Good question: yeah.. I guess the changes file is the right place... update that file and then I'll take that material and put it into the release blurb when I push it out.

**Comment by crocogorical** [comment]
@brifordwylie, I've updated CHANGES and merged to master in d4d367fd0a8371643d779b9b5b7257c79e560593.

**Comment by brifordwylie** [comment]
Great 👍
