### ISSUE TITLE
do not recognise CipherSuite 0x1301 TLS_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by RonaldinhoL** [kbandla/dpkt#559]
seems its  tls1.3 [RFC8446]

**Comment by arunpalaniappan** [comment]
Try downgrading dpkt to version 1.9.3 or lower. Had the same issue and downgrading resolved it.

**Comment by RonaldinhoL** [comment]
for tmp solution, i have edited  dpkt code  and added some tls1.3 suite to it and it worked.

**Comment by brifordwylie** [comment]
Hmm... @RonaldinhoL since we have a skeleton crew of maintainers... could you provide:
- A PR (best)
- More detail (also good)

**Comment by obormot** [comment]
@RonaldinhoL We welcome pull requests! If your change solves the issue you raised this sounds like a perfect candidate for a contribution. 

I've drafted this change, is this similar to what you have in mind?  https://github.com/kbandla/dpkt/commit/a67f5887fd8fec6d62fd80e46c67dfaa32afb299

**Comment by RonaldinhoL** [comment]
> @RonaldinhoL We welcome pull requests! If your change solves the issue you raised this sounds like a perfect candidate for a contribution.
> 
> I've drafted this change, is this similar to what you have in mind? [a67f588](https://github.com/kbandla/dpkt/commit/a67f5887fd8fec6d62fd80e46c67dfaa32afb299)

yes, i did same as you

**Comment by obormot** [comment]
change merged, closing
