### ISSUE TITLE
A bug in construction of ipv6 fragments extension header

### ISSUE THREAD

**Issue by galosss** [kbandla/dpkt#560]
in `IP6FragmentHeader` , the implemented setter of `m_flag` is using the mask `~0xfffe`, as follows:

    @m_flag.setter
    def m_flag(self, v):
        self.frag_off_resv_m = (self.frag_off_resv_m & ~0xfffe) | v

while the mask should be `0xfffe` , without negating `~`.
it fails the construction of the packet as a result.

thanks!

**Comment by obormot** [comment]
good catch!
