### ISSUE TITLE
a bug in IPv6 Packet's length calculation

### ISSUE THREAD

**Issue by galosss** [kbandla/dpkt#563]
Hey there,

there's a bug in IPv6 packets length calculation, using `len(packet)`.
IPv6 packet uses the default `__len__` implementation of dpkt.Packet, but doesn't take the extensions header into account.
It's leading to a bug in length calculation when extensions headers are used, and `len(bytes(packet)) > len(packet)`.

thanks.

**Comment by galosss** [comment]
the fix could be 
```
def __len__(self):
    return super().__len__() + len(self.headers_str()[1])
```

**Comment by obormot** [comment]
Hi @galosss please see if the referenced PR https://github.com/kbandla/dpkt/pull/566 fixes the issue

**Comment by galosss** [comment]
yeah it looks good. tnx!

why do you prefer clone some extension headers parse code rather than use `len(self.headers_str()[1])` as suggested above?

thanks,
Gal

**Comment by obormot** [comment]
@galosss Thanks! In general we want to avoid serialization (or packing into str/bytes), when we're only trying to calculate the size. My solution does repeat some code but avoids serialization.
