### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by galosss** [kbandla/dpkt#568]
Hey,

Could you please distribute a new release version (including the last 2 fixes of my issues).

Thanks,
Gal

**Comment by brifordwylie** [comment]
@galosss @stryker2k2 okay.. so 1.9.6 is now up on PyPi, I literally had to squeeze this in during a 15 minute opening in my day :)

So I'd ask the favor for two things:
- Test it for the new changes
- Give me some text for the release notes

**Comment by stryker2k2** [comment]
You rock, @brifordwylie!  I will absolutely test it out throughout the day as well as Monday and I'll provide feedback and notes here in this issue thread.

**Comment by stryker2k2** [comment]
@brifordwylie - I've removed all of my dpkt repos that I've cloned and installed the dkpt 1.9.6 from PyPI and it works flawlessly.

```
Change Log:
- Added in the TLS 1.3 Cipher Suite from the RFC 8446 dated August 2018
```

You all are amazing! Thanks a ton for the update!

**Comment by obormot** [comment]
@brifordwylie can the issue be closed now?

**Comment by obormot** [comment]
I think this can be closed
