### ISSUE TITLE
3rd party documentation link is dead

### ISSUE THREAD

**Issue by obormot** [kbandla/dpkt#590]
**Describe the bug**
docs/examples.rst has a documentation link that no longer works
```
Jeff Silverman Docs/Code
------------------------
`Jeff Silverman <https://github.com/jeffsilverm>`__ has some
`code <https://github.com/jeffsilverm/dpkt_doc>`__ and
`documentation <http://www.commercialventvac.com/dpkt.html>`__.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1717834/122441583-8759a880-cf52-11eb-8cda-bddfff02161d.png)

**Comment by brifordwylie** [comment]
Should be fixed as part of https://github.com/kbandla/dpkt/issues/503

**Comment by obormot** [comment]
@brifordwylie Sooo with #503 now closed I looked at this issue again. 
The original link is still dead, but is available on the Web archive https://web.archive.org/web/20190917143546/http://www.commercialventvac.com/dpkt.html

Looks like most of it was written around 2010, seems useful, but is it worth attempting to salvage? 
Anyway, I'll update the link in the doc.
