### ISSUE TITLE
Generated file stats with 0xD4C3B2A1

### ISSUE THREAD

**Issue by Isdriai** [kbandla/dpkt#592]
**Describe the bug**
When I use pcap.Writer or pcapng.Writer, I have a pcap file starting with the magic number "0xD4C3B2A1".
Is it the normal behavior ? Because I want the magic number be 0xa1b2c3d4 or 0xd4c3b2a1 and I didn't see solution in the doc or the source code 

**To Reproduce**
I use pcap.Writer or pcapng.Writer

**Expected behavior**
I want 0xa1b2c3d4 or 0xd4c3b2a1 as magic number

**Details(please complete the following information):**
 - OS: manjaro linux 
 - Python Version 3.9.5

**Comment by obormot** [comment]
0xD4C3B2A1 is the same number as 0xd4c3b2a1 , what's your concern here exactly @Isdriai ?
