### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by obormot** [kbandla/dpkt#599]
TODO
- [x] create a PR ( @obormot  #600 )
- [x] update changelog ( @obormot )
- [x] decide whether the new release should be 1.9.7 or a 2.0 ( @brifordwylie  @kbandla )
- [x] switch the docs from from RST to MarkDown (#503 @brifordwylie )
- [x] make sure the docs are updated and correctly reference the new `creating_parsers` doc
- [x] do the release thing

**Comment by brifordwylie** [comment]
On the issue of version.. I really have no preference... I'll leave it up to @obormot

**Comment by brifordwylie** [comment]
The creating parsers doc is now linked in the new docs: <https://kbandla.github.io/dpkt/> under 'DPKT Key Concepts for Creating Parsers'

**Comment by obormot** [comment]
> On the issue of version.. I really have no preference... I'll leave it up to @obormot

I'm fine with 1.9.7. In 2.0 we can deprecate Python2; it'll be nice to have all the new features added in this release still be available in pre-2.0 release IMO.

> The creating parsers doc is now linked in the new docs

Thanks!  I've noticed a couple formatting issues there, will fix them before we publish the release.

**Comment by obormot** [comment]
creating parsers md doc is now fixed
