### ISSUE TITLE
The HTTP response message is divided into multiple TCP messages.

### ISSUE THREAD

**Issue by Gu-f** [kbandla/dpkt#629]
The HTTP response message is divided into multiple TCP messages. How should I unpack HTTP.
It looks like this:
```
==== TCP1
b'HTTP/1.0 200 OK\r\n'
==== TCP2 (response_header)
b'Content-Type: text/html; charset=utf-8\r\nContent-Length: 910\r\nServer: Werkzeug/1.0.1 Python/3.7.8\r\n\r\n'
==== TCP3 (response_body)
b'<pre><code id="jsondata" style="font-size:18px"></code></pre>'
```
It makes it impossible for me to use dpkt.http.Response(tcp.data) directly

**Comment by brifordwylie** [comment]
@Gu-f Dpkt is just handling simple packet parsing. The package does not provide support for reconstructing ‘flows’ (See the TCP Reassembly section in  https://www.wireshark.org/docs/wsug_html_chunked/ChAdvReassemblySection.html). A HTTP request (and response if you tried to parse it) will only parse correctly if they fit within a single packet. Requests can often fit in a single packet but Responses almost never will.
