### ISSUE TITLE
support for "modified pcaps"

### ISSUE THREAD

**Issue by oosthoek** [kbandla/dpkt#632]
currently the dpkt.pcap.Reader does not support  "[modified pcaps](https://wiki.wireshark.org/Development/LibpcapFileFormat#modified-pcap)".  are there any plans to add this?

**Comment by obormot** [comment]
No plans to add, but looks like the format is mainly different in the header. It should be pretty straightforward to customize the existing dpkt.pcap.FileHdr to include additional fields, and modify the "magic" signature, in the specific application. Pull requests are always welcome too :)
