### ISSUE TITLE
bitfield unittest might be platform dependant

### ISSUE THREAD

**Issue by AiyionPrime** [kbandla/dpkt#644]
This test gives me trouble.

https://github.com/kbandla/dpkt/blob/2d30526422d48f83d4f724221d9ae0dcd5ff57fe/dpkt/dpkt.py#L62-L65

I think it should not be called on `ph_struct` but a concat of the classes `__byte_order__` and it, no?

On my system the test tells me `L` is expected to be 8*8bits instead of 32, I'd expect.
https://docs.python.org/3/library/struct.html#format-characters

Am I just overlooking something? I'll provide a PR with a unittest with what I mean tomorrow, if wanted.

**Comment by obormot** [comment]
A piece of code to replicate the issue would be helpful, yes. 
`__byte_order__` isn't related to sizing, I don't think it needs to be involved.

**Comment by AiyionPrime** [comment]
I'll provide the example tomorrow morning, then.

**Comment by AiyionPrime** [comment]
I've got a working unittest, as well as a draft for a fix.
It will take a little while longer though, due to company policies - sorry for the wait.

**Comment by AiyionPrime** [comment]
@obormot This took way longer than anticipated.
Future contributions should be faster.
