### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by FeldrinH** [kbandla/dpkt#659]
Not really a bug report, but this seems like the most relevant place for it.
Dpkt hasn't had a release for more than a year and hasn't had any public commits to the repo in almost a year. Is the library still being maintained?

**Comment by kbandla** [comment]
Hey @FeldrinH. Yes its been a little slow. Anything I can help with?

**Comment by FeldrinH** [comment]
That's great to hear! This is a great alterantive to Scipy and I am happy that it is still being developed. I've already opened https://github.com/kbandla/dpkt/issues/660 about the limitation that motivated me to ask this question.
