### ISSUE TITLE
dpkt unable to parse the PCAP file with packets that are captured with specific snaplength

### ISSUE THREAD

**Issue by sksm2822** [kbandla/dpkt#664]
**Describe the bug**
Python script that uses dpkt module to analyse the packets is unable to parse the pcap file that contains packets that are captured with a specific snaplength (for example 128 bytes). PCAP files with full packet size always works fine.

**To Reproduce**
Run a quick packet capture with a smaller snaplegth set for example 128 bytes, use them with the python script utilizing dpkt

**Expected behavior**
AttributeError: 'TCP' object has no attribute 'seq'

**Screenshots**
![image](https://github.com/kbandla/dpkt/assets/163015278/c3e6604b-0116-4a88-b6b3-6c6007406b19)

**Details(please complete the following information):**
 - OS: [Windows / MacOS]
 - Python Version [3.12.0 ]

**Additional context**
Tried PCAP files with different snaplength and encountered similar error.
###Below is my python script that I used to reproduced this error###
import os
import dpkt

def remove_duplicate_packets(pcap_file):
    unique_packets = []
    seen_packets = set()

    # Determine the output file path
    output_file = os.path.splitext(pcap_file)[0] + "_unique.pcap"

    with open(pcap_file, 'rb') as file:
        pcap_reader = dpkt.pcap.Reader(file)

        for timestamp, packet_data in pcap_reader:
            ethernet_frame = dpkt.ethernet.Ethernet(packet_data)
            ip_packet = ethernet_frame.data
            tcp_packet = ip_packet.data

            frame_length = len(packet_data)
            seq_number = tcp_packet.seq
            ack_number = tcp_packet.ack
            ip_id = ip_packet.id

            packet_info = (frame_length, seq_number, ack_number, ip_id)

            if packet_info not in seen_packets:
                seen_packets.add(packet_info)
                unique_packets.append((timestamp, packet_data))

    # Writing the unique packets to a new pcap file
    with open(output_file, 'wb') as file:
        pcap_writer = dpkt.pcap.Writer(file)
        for timestamp, packet_data in unique_packets:
            pcap_writer.writepkt(packet_data, timestamp)

    print("Duplicate packets removed. Unique packets saved in", output_file)

# Prompt for the input file
pcap_file = input("Enter the path to the input PCAP file: ")
remove_duplicate_packets(pcap_file)

**Comment by obormot** [comment]
I don't think the error you're seeing is caused by the snaplen. Limited at 128 bytes TCP packets would still include the ack and seq numbers. Likely there are some UDP packets in the pcap, which dpkt recognizes, and they don't have ack and seq fields, hence the error you're seeing is likely correct. Try the following and see if it helps:
```
        ip_packet = ethernet_frame.data
        tcp_packet = ip_packet.data

        if not isinstance(tcp_packet, dpkt.tcp.TCP):
            continue

        frame_length = len(packet_data)         
```
