### ISSUE TITLE
problem with mpls decapsulation

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#89]
_From [toby.bea...@gmail.com](https://code.google.com/u/104115839347211898201/) on January 23, 2011 17:06:35_

What steps will reproduce the problem? 1. Analyzing mpls encapsulated packets What is the expected output? What do you see instead? I open a pcap file with multiple mpls layers on each packet.  When I try to iterate through, it has eth.data as a type str instead of dpkt.ip.IP.  If I try forcing ip on eth(data) I get "dpkt.dpkt.UnpackError: invalid header length"

for ts, data in pcapreader:
    try: eth = dpkt.ethernet.Ethernet(data)
    except: continue
    print eth.type
    ip = dpkt.ip.IP(eth.data)

2048
Traceback (most recent call last):
  File "pcap-parse.py"
, line 14, in <module>
    ip = dpkt.ip.IP(eth.data)
  File "c:\Python27\lib\site-packages\dpkt\dpkt.py", line 72, in **init**
    self.unpack(args[0])
  File "c:\Python27\lib\site-packages\dpkt\ip.py", line 56, in unpack
    raise dpkt.UnpackError, 'invalid header length'
dpkt.dpkt.UnpackError: invalid header length What version of the product are you using? On what operating system? 1.7 Please provide any additional information below.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=62_

**Comment by kbandla** [comment]
_From [toby.bea...@gmail.com](https://code.google.com/u/104115839347211898201/) on January 24, 2011 14:25:23_

Seems to be breaking in ip.py during the unpack.

def unpack(self, buf):
        dpkt.Packet.unpack(self, buf)
        ol = ((self.v_hl & 0xf) \<< 2) - self.__hdr_len__
        if ol \< 0:  

in my debug self.v_hl = 1, self.__hdr_len__ = 20, and ol = -16.

**Comment by obormot** [comment]
cleaning up old issues
this is likely fixed with multiple MPLS improvements made and unit tests added
