### ISSUE TITLE
dpkt does not support pflog dumps

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#93]
_From [elektros...@googlemail.com](https://code.google.com/u/116803648421931677641/) on March 06, 2011 06:16:39_

What steps will reproduce the problem? 1. Make a dump with tcpdump -i pflog0 on OpenBSD
2. Try to read the dump with dpkt What version of the product are you using? On what operating system? dpkt-1.7 on Gentoo Linux/OpenBSD

I wrote a Pflog class, which makes it possible to read pflog dumps.
The class is attached.

Maybe you could include this in a future release :).

**Attachment:** [pflog.py](http://code.google.com/p/dpkt/issues/detail?id=66)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=66_

**Comment by brifordwylie** [comment]
Closing, if someone really wants PFlog support we can reopen.

**Comment by forkd** [comment]
Hey guys, sorry for posting in this old thread, but I'm facing the same problem: trying to parse a pflog file and dpkt doesn't work. I tried to use that class on the first message, but link is broken. Will you support pflog? Thanks.

**Comment by brifordwylie** [comment]
@forkd @kbandla pflog support comes down to how many people are going to use it and is someone willing to put in a PR for it. I noticed that the pflog.py attachment is now 'gone'. So TBH I have NO experience with pflog at all, so shrug... My suggestion is that we try to locate the pflog.py file and someone does some testing and puts in a PR for it.

**Comment by forkd** [comment]
Is this the referred [pflog.py](https://github.com/levigross/Scapy/blob/master/scapy/layers/pflog.py)? I have no experience writting this kind of code, but I could try since I have some Python knowledge, networking background, and an OpenBSD system here.

**Comment by obormot** [comment]
This is definitely not the referred pflog.py (it's from scapy) but it can be used as a reference.
