### ISSUE TITLE
Patch for /trunk/dpkt/vrrp.py

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#95]
_From [kyle.creyts@gmail.com](https://code.google.com/u/kyle.creyts@gmail.com/) on April 07, 2011 13:49:03_

noticed this, you might want to look it over. I am pretty sure its right, but I haven't tested it yet because I'm lazy.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=68_

**Comment by kbandla** [comment]
_From [kyle.creyts@gmail.com](https://code.google.com/u/kyle.creyts@gmail.com/) on April 13, 2011 13:10:38_

you can close this issue. patch was incorrect, debugging further.

**Comment by brifordwylie** [comment]
@kbandla do we have any additional information here? When I click back to the original google issue there's basically no information. If there's no addition info.. we should just close this.

**Comment by kbandla** [comment]
yeah, it looks invalid. closing this.
